## 讀取資料 (Default：Label Encoding)

In [107]:
#讀取資料
import pandas as pd
import numpy as np
# plots
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df= pd.read_csv('Default_Fin.csv')

In [108]:
# all columns
print(list(df.columns))
# PO%；333/10000 (3.33%)

['Index', 'Employed', 'Bank Balance', 'Annual Salary', 'Defaulted?']


In [109]:
#資料前處理 #沒有 Label Encoder
df=df.dropna(axis=0) #有遺失值，即丟棄該樣本
y=df['Defaulted?']#應變數

X=df.drop(columns='Index') 
X=X.drop(columns='Defaulted?') #丟棄應變數

In [110]:
y

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: Defaulted?, Length: 10000, dtype: int64

In [111]:
X

Employed  Bank Balance  Annual Salary
0            1       8754.36      532339.56
1            0       9806.16      145273.56
2            1      12882.60      381205.68
3            1       6351.00      428453.88
4            1       9427.92      461562.00
...        ...           ...            ...
9995         1       8538.72      635908.56
9996         1       9095.52      235928.64
9997         1      10144.92      703633.92
9998         1      18828.12      440029.32
9999         0       2411.04      202355.40

[10000 rows x 3 columns]

## P1：標準化是否影響結果

In [112]:
#先不經標準化做XGBoost
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf1= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores1 = cross_val_score(clf1,X,y,cv=5,scoring='accuracy')
print(scores1)
print('Accuracy of XGBoost cross-vaild test:',scores1.mean())
# Accuracy of XGBoost cross-vaild test: 0.935065196935072

[0.968  0.971  0.963  0.967  0.9675]
Accuracy of XGBoost cross-vaild test: 0.9673


In [113]:
#使用經過LabelEncoder編碼的特徵，標準化 (因為變數值間有大有小)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X1 = sc.fit_transform(X)

In [114]:
#標準化後XGBoost
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf11= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores11 = cross_val_score(clf11,X1,y,cv=5,scoring='accuracy')
print(scores11)
print('Accuracy of XGBoost cross-vaild test:',scores11.mean())

# Accuracy of XGBoost cross-vaild test: 0.9362212662992337
##標準化在XGBoost的交叉驗證上沒有差異太大

[0.968  0.971  0.963  0.967  0.9675]
Accuracy of XGBoost cross-vaild test: 0.9673


## P3：Feature Binning 有沒有效果

In [115]:
import pandas as pd
import numpy as np
# For 繪製敘述統計
import matplotlib.pyplot as plt
%matplotlib inline
import pylab
import scipy.stats as stats
from sklearn.model_selection import train_test_split
# for discretization
from sklearn.preprocessing import KBinsDiscretizer

In [116]:
X

Employed  Bank Balance  Annual Salary
0            1       8754.36      532339.56
1            0       9806.16      145273.56
2            1      12882.60      381205.68
3            1       6351.00      428453.88
4            1       9427.92      461562.00
...        ...           ...            ...
9995         1       8538.72      635908.56
9996         1       9095.52      235928.64
9997         1      10144.92      703633.92
9998         1      18828.12      440029.32
9999         0       2411.04      202355.40

[10000 rows x 3 columns]

In [117]:
# Equal width Binning
disc1 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
disc1.fit(X[['Bank Balance']])
disc2 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
disc2.fit(X[['Annual Salary']])

KBinsDiscretizer(encode='ordinal', n_bins=10, strategy='uniform')

In [118]:
# Equal Frequency Binning
disc11 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
disc11.fit(X[['Bank Balance']])
disc21 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
disc21.fit(X[['Annual Salary']])

KBinsDiscretizer(encode='ordinal', n_bins=10)

In [119]:
disc1.bin_edges_

array([array([    0.   ,  3185.184,  6370.368,  9555.552, 12740.736, 15925.92 ,
              19111.104, 22296.288, 25481.472, 28666.656, 31851.84 ])          ],
      dtype=object)

In [120]:
disc11.bin_edges_

array([array([    0.   ,  2166.9  ,  4744.584,  6739.44 ,  8365.896,  9883.62 ,
              11415.   , 13034.196, 14997.48 , 17659.524, 31851.84 ])          ],
      dtype=object)

In [121]:
X3 = pd.DataFrame(X)
X3[['Bank Balance']]=disc1.transform(X[['Bank Balance']])
X3[['Annual Salary']]=disc2.transform(X[['Annual Salary']])
X3 = pd.DataFrame(X3)

In [122]:
X3

Employed  Bank Balance  Annual Salary
0            1           2.0            5.0
1            0           3.0            1.0
2            1           4.0            4.0
3            1           1.0            4.0
4            1           2.0            5.0
...        ...           ...            ...
9995         1           2.0            7.0
9996         1           2.0            2.0
9997         1           3.0            7.0
9998         1           5.0            4.0
9999         0           0.0            2.0

[10000 rows x 3 columns]

In [123]:
# Binning 後進行 XGBoost
#X3=X3.drop(columns=['age',' fnlwgt',' capital-gain',' capital-loss',' hours-per-week']) #原先的特徵丟掉

from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf3= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores3 = cross_val_score(clf3,X3,y,cv=5,scoring='accuracy')
print(scores3)
print('Accuracy of XGBoost cross-vaild test:',scores3.mean())

#Accuracy of XGBoost cross-vaild test: 0.9304140341443743
# Frequency較佳

[0.972  0.974  0.9705 0.969  0.9695]
Accuracy of XGBoost cross-vaild test: 0.9710000000000001


In [124]:
#資料前處理 #沒有 Label Encoder
df= pd.read_csv('Default_Fin.csv')
df=df.dropna(axis=0) #有遺失值，即丟棄該樣本
y=df['Defaulted?']#應變數

X=df.drop(columns='Index')
X=df.drop(columns='Defaulted?') #丟棄應變數
X31 = pd.DataFrame(X) #inherit

X31[['Bank Balance']]=disc11.transform(X[['Bank Balance']])
X31[['Annual Salary']]=disc21.transform(X[['Annual Salary']])
X31 = pd.DataFrame(X31)

In [125]:
X31

Index  Employed  Bank Balance  Annual Salary
0         1         1           4.0            7.0
1         2         0           4.0            0.0
2         3         1           6.0            4.0
3         4         1           2.0            5.0
4         5         1           4.0            6.0
...     ...       ...           ...            ...
9995   9996         1           4.0            9.0
9996   9997         1           4.0            2.0
9997   9998         1           5.0            9.0
9998   9999         1           9.0            5.0
9999  10000         0           1.0            1.0

[10000 rows x 4 columns]

In [126]:
# Binning 後進行 XGBoost
#X3=X3.drop(columns=['age',' fnlwgt',' capital-gain',' capital-loss',' hours-per-week']) #原先的特徵丟掉

from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf3= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores31 = cross_val_score(clf3,X31,y,cv=5,scoring='accuracy')
print(scores31)
print('Accuracy of XGBoost cross-vaild test:',scores31.mean())

#Accuracy of XGBoost cross-vaild test:  0.935065196935072
# Frequency較佳

[0.926  0.902  0.9665 0.9665 0.9665]
Accuracy of XGBoost cross-vaild test: 0.9455


Source：iT幫幫忙--Day12 - Feature Engineering -- 4. 分隔方法(Discretization),https://ithelp.ithome.com.tw/articles/10235726

## P2：One-hot Encoding vs. Label Encoding on Tree-based method

In [127]:
X3

Employed  Bank Balance  Annual Salary
0            1           2.0            5.0
1            0           3.0            1.0
2            1           4.0            4.0
3            1           1.0            4.0
4            1           2.0            5.0
...        ...           ...            ...
9995         1           2.0            7.0
9996         1           2.0            2.0
9997         1           3.0            7.0
9998         1           5.0            4.0
9999         0           0.0            2.0

[10000 rows x 3 columns]

In [128]:
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [129]:
from category_encoders import *
enc2 = OneHotEncoder(cols=['Bank Balance','Annual Salary']).fit(X3,y)
X2 = enc2.transform(X3)
X2 = pd.DataFrame(X2)
X2

Employed  Bank Balance_1  Bank Balance_2  Bank Balance_3  \
0            1               1               0               0   
1            0               0               1               0   
2            1               0               0               1   
3            1               0               0               0   
4            1               1               0               0   
...        ...             ...             ...             ...   
9995         1               1               0               0   
9996         1               1               0               0   
9997         1               0               1               0   
9998         1               0               0               0   
9999         0               0               0               0   

      Bank Balance_4  Bank Balance_5  Bank Balance_6  Bank Balance_7  \
0                  0               0               0               0   
1                  0               0               0               0   
2                  0               0               0               0   
3                  1               0               0               0   
4                  0               0               0               0   
...              ...             ...             ...             ...   
9995               0               0               0               0   
9996               0               0               0               0   
9997               0               0               0               0   
9998               0               0               1               0   
9999               0               1               0               0   

      Bank Balance_8  Bank Balance_9  ...  Annual Salary_1  Annual Salary_2  \
0                  0               0  ...                1                0   
1                  0               0  ...                0                1   
2                  0               0  ...                0                0   
3                  0               0  ...                0                0   
4                  0               0  ...                1                0   
...              ...             ...  ...              ...              ...   
9995               0               0  ...                0                0   
9996               0               0  ...                0                0   
9997               0               0  ...                0                0   
9998               0               0  ...                0                0   
9999               0               0  ...                0                0   

      Annual Salary_3  Annual Salary_4  Annual Salary_5  Annual Salary_6  \
0                   0                0                0                0   
1                   0                0                0                0   
2                   1                0                0                0   
3                   1                0                0                0   
4                   0                0                0                0   
...               ...              ...              ...              ...   
9995                0                0                0                0   
9996                0                0                0                1   
9997                0                0                0                0   
9998                1                0                0                0   
9999                0                0                0                1   

      Annual Salary_7  Annual Salary_8  Annual Salary_9  Annual Salary_10  
0                   0                0                0                 0  
1                   0                0                0                 0  
2                   0                0                0                 0  
3                   0                0                0                 0  
4                   0                0                0                 0  
...               ...         

In [130]:
# One hot encoding 後 XGBoost
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf2= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores2 = cross_val_score(clf2,X3,y,cv=5,scoring='accuracy')
print(scores2)
print('Accuracy of XGBoost cross-vaild test:',scores2.mean())

# Accuracy of XGBoost cross-vaild test for Label Encoder: 0.9362212662992337
# Accuracy of XGBoost cross-vaild test for one-hot encoding: 0.9420217771205808
# 交叉驗證為 Label Encoder 結果略佳
# 可能在 one-hot encoding 會陷入 curse of dimensionaility

[0.972  0.974  0.9705 0.969  0.9695]
Accuracy of XGBoost cross-vaild test: 0.9710000000000001


## P4：Label Encoding

In [131]:
df= pd.read_csv('Default_Fin.csv')
df=df.dropna(axis=0) #有遺失值，即丟棄該樣本
y=df['Defaulted?']#應變數
X=df.drop(columns='Index') #丟棄應變數
X=X.drop(columns='Defaulted?')
X

Employed  Bank Balance  Annual Salary
0            1       8754.36      532339.56
1            0       9806.16      145273.56
2            1      12882.60      381205.68
3            1       6351.00      428453.88
4            1       9427.92      461562.00
...        ...           ...            ...
9995         1       8538.72      635908.56
9996         1       9095.52      235928.64
9997         1      10144.92      703633.92
9998         1      18828.12      440029.32
9999         0       2411.04      202355.40

[10000 rows x 3 columns]

In [132]:
# One hot encoding 後 XGBoost 
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf4= XGBClassifier(**params)

# 5-fold validation
scores4 = cross_val_score(clf4,X,y,cv=5,scoring='accuracy')
print(scores4)
print('Accuracy of XGBoost cross-vaild test:',scores4.mean())

# Accuracy of XGBoost cross-vaild test: 0.9408522650893938

[0.968  0.971  0.963  0.967  0.9675]
Accuracy of XGBoost cross-vaild test: 0.9673


In [133]:
# One hot encoding 後 RandomForest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100)
clf41=RF.fit(X,y)
scores41 = cross_val_score(clf41,X,y,cv=5,scoring='accuracy')
print(scores41)
print('Accuracy of RandomForest cross-vaild test:',scores41.mean())

# Accuracy of RandomForest cross-vaild test: 0.9327261728726979

[0.97   0.9695 0.968  0.971  0.9685]
Accuracy of RandomForest cross-vaild test: 0.9693999999999999


In [134]:
# One hot encoding 後 Lightgbm
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(application='multiclass', boosting='gbdt', learning_rate=0.1, max_depth=-5, feature_fraction=0.5, random_state=42)
clf42=LGBM.fit(X,y)
scores42 = cross_val_score(clf42,X,y,cv=5,scoring='accuracy')
print(scores42)
print('Accuracy of Lightgbm cross-vaild test:',scores42.mean())

# Accuracy of Lightgbm cross-vaild test: 0.9373706143298831

[0.9725 0.974  0.9685 0.9735 0.969 ]
Accuracy of Lightgbm cross-vaild test: 0.9715


In [135]:
# One hot encoding 後 MLP
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes = (256,128,64,32), activation="relu",max_iter=50, random_state=1)
clf43=MLP.fit(X,y)
scores43 = cross_val_score(clf43,X,y,cv=5,scoring='accuracy')
print(scores43)
print('Accuracy of MLP cross-vaild test:',scores43.mean())
# Accuracy of MLP cross-vaild test: 0.7034816507595107

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.967  0.966  0.966  0.966  0.9605]
Accuracy of MLP cross-vaild test: 0.9651


In [136]:
# One hot encoding 後 SVM
from sklearn import svm
from sklearn import svm, metrics
from sklearn.metrics import accuracy_score

svm = svm.SVC(kernel='rbf',max_iter=10000) #Default: rbf
clf44=svm.fit(X,y)
scores44 = cross_val_score(clf44,X,y,cv=5,scoring='accuracy')
print(scores44)
print('Accuracy of SVM cross-vaild test:',scores44.mean())
# Accuracy of SVM cross-vaild test: 0.8364296276381233

[0.967  0.967  0.9665 0.9665 0.9665]
Accuracy of SVM cross-vaild test: 0.9667


## P4：One Hot Encoding

In [137]:
# 清除 Label Encoder 後，再做 One Hot Encoding
X2

Employed  Bank Balance_1  Bank Balance_2  Bank Balance_3  \
0            1               1               0               0   
1            0               0               1               0   
2            1               0               0               1   
3            1               0               0               0   
4            1               1               0               0   
...        ...             ...             ...             ...   
9995         1               1               0               0   
9996         1               1               0               0   
9997         1               0               1               0   
9998         1               0               0               0   
9999         0               0               0               0   

      Bank Balance_4  Bank Balance_5  Bank Balance_6  Bank Balance_7  \
0                  0               0               0               0   
1                  0               0               0               0   
2                  0               0               0               0   
3                  1               0               0               0   
4                  0               0               0               0   
...              ...             ...             ...             ...   
9995               0               0               0               0   
9996               0               0               0               0   
9997               0               0               0               0   
9998               0               0               1               0   
9999               0               1               0               0   

      Bank Balance_8  Bank Balance_9  ...  Annual Salary_1  Annual Salary_2  \
0                  0               0  ...                1                0   
1                  0               0  ...                0                1   
2                  0               0  ...                0                0   
3                  0               0  ...                0                0   
4                  0               0  ...                1                0   
...              ...             ...  ...              ...              ...   
9995               0               0  ...                0                0   
9996               0               0  ...                0                0   
9997               0               0  ...                0                0   
9998               0               0  ...                0                0   
9999               0               0  ...                0                0   

      Annual Salary_3  Annual Salary_4  Annual Salary_5  Annual Salary_6  \
0                   0                0                0                0   
1                   0                0                0                0   
2                   1                0                0                0   
3                   1                0                0                0   
4                   0                0                0                0   
...               ...              ...              ...              ...   
9995                0                0                0                0   
9996                0                0                0                1   
9997                0                0                0                0   
9998                1                0                0                0   
9999                0                0                0                1   

      Annual Salary_7  Annual Salary_8  Annual Salary_9  Annual Salary_10  
0                   0                0                0                 0  
1                   0                0                0                 0  
2                   0                0                0                 0  
3                   0                0                0                 0  
4                   0                0                0                 0  
...               ...         

In [138]:
# One hot encoding 後 XGBoost / 前處理在 P2
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf4= XGBClassifier(**params)

# 5-fold validation
scores4a = cross_val_score(clf4,X2,y,cv=5,scoring='accuracy')
print(scores4a)
print('Accuracy of XGBoost cross-vaild test:',scores4a.mean())
# Accuracy of XGBoost cross-vaild test: 0.9420217771205808

[0.97   0.974  0.971  0.9685 0.9695]
Accuracy of XGBoost cross-vaild test: 0.9705999999999999


In [139]:
# One hot encoding 後 RandomForest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100)
clf41=RF.fit(X2,y)
scores41a = cross_val_score(clf41,X2,y,cv=5,scoring='accuracy')
print(scores41a)
print('Accuracy of RandomForest cross-vaild test:',scores41a.mean())

# Accuracy of RandomForest cross-vaild test: 0.9223215485952412

[0.969  0.974  0.97   0.969  0.9695]
Accuracy of RandomForest cross-vaild test: 0.9702999999999999


In [140]:
# One hot encoding 後 Lightgbm
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(application='multiclass', boosting='gbdt', learning_rate=0.1, max_depth=-5, feature_fraction=0.5, random_state=42)
clf42=LGBM.fit(X2,y)
scores42a = cross_val_score(clf42,X2,y,cv=5,scoring='accuracy')
print(scores42a)
print('Accuracy of Lightgbm cross-vaild test:',scores42a.mean())

# Accuracy of Lightgbm cross-vaild test: 0.9362212662992337

[0.969  0.974  0.9705 0.968  0.9695]
Accuracy of Lightgbm cross-vaild test: 0.9702


In [141]:
# One hot encoding 後 MLP
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes = (256,128,64,32), activation="relu",max_iter=50, random_state=1)
clf43=MLP.fit(X2,y)
scores43a = cross_val_score(clf43,X2,y,cv=5,scoring='accuracy')
print(scores43a)
print('Accuracy of MLP cross-vaild test:',scores43a.mean())
# Accuracy of MLP cross-vaild test: 0.8364296276381233

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.9695 0.9745 0.97   0.969  0.9685]
Accuracy of MLP cross-vaild test: 0.9702999999999999


In [142]:
# One hot encoding 後 SVM
from sklearn import svm
from sklearn import svm, metrics
from sklearn.metrics import accuracy_score

svm = svm.SVC(kernel='rbf',max_iter=10000) #Default: rbf
clf44=svm.fit(X2,y)
scores44a = cross_val_score(clf44,X2,y,cv=5,scoring='accuracy')
print(scores44a)
print('Accuracy of SVM cross-vaild test:',scores44a.mean())
# Accuracy of SVM cross-vaild test for one-hot encoding: 0.8364296276381233

[0.9715 0.973  0.9705 0.9695 0.9695]
Accuracy of SVM cross-vaild test: 0.9708


## P4：Frequency Encoding

In [143]:
# Frequency encoding：用類別出現頻率當作該類別數值
X

Employed  Bank Balance  Annual Salary
0            1       8754.36      532339.56
1            0       9806.16      145273.56
2            1      12882.60      381205.68
3            1       6351.00      428453.88
4            1       9427.92      461562.00
...        ...           ...            ...
9995         1       8538.72      635908.56
9996         1       9095.52      235928.64
9997         1      10144.92      703633.92
9998         1      18828.12      440029.32
9999         0       2411.04      202355.40

[10000 rows x 3 columns]

In [144]:
X4b=pd.DataFrame(X)
encwork=X4b['Employed'].value_counts()
X4b['Employed']=X4b['Employed'].apply(lambda x : encwork[x]) 

In [145]:
X4b

Employed  Bank Balance  Annual Salary
0         7056       8754.36      532339.56
1         2944       9806.16      145273.56
2         7056      12882.60      381205.68
3         7056       6351.00      428453.88
4         7056       9427.92      461562.00
...        ...           ...            ...
9995      7056       8538.72      635908.56
9996      7056       9095.52      235928.64
9997      7056      10144.92      703633.92
9998      7056      18828.12      440029.32
9999      2944       2411.04      202355.40

[10000 rows x 3 columns]

In [146]:
# Frequency encoding 後 XGBoost / 前處理在 P2
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf4b= XGBClassifier(**params)

# 5-fold validation
scores4b = cross_val_score(clf4b,X4b,y,cv=5,scoring='accuracy')
print(scores4b)
print('Accuracy of XGBoost cross-vaild test:',scores4b.mean())

# Accuracy of XGBoost cross-vaild test: 0.936194380965183

[0.968  0.971  0.963  0.967  0.9675]
Accuracy of XGBoost cross-vaild test: 0.9673


In [147]:
# Frequency encoding 後 RandomForest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100)
clf41b=RF.fit(X4b,y)
scores41b = cross_val_score(clf41b,X4b,y,cv=5,scoring='accuracy')
print(scores41b)
print('Accuracy of RandomForest cross-vaild test:',scores41b.mean())

# Accuracy of RandomForest cross-vaild test: 0.9315633821750235

[0.9715 0.9705 0.968  0.969  0.9665]
Accuracy of RandomForest cross-vaild test: 0.9691000000000001


In [148]:
# Frequency encoding 後 Lightgbm
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(application='multiclass', boosting='gbdt', learning_rate=0.1, max_depth=-5, feature_fraction=0.5, random_state=42)
clf42b=LGBM.fit(X4b,y)
scores42b = cross_val_score(clf42b,X4b,y,cv=5,scoring='accuracy')
print(scores42b)
print('Accuracy of Lightgbm cross-vaild test:',scores42b.mean())
# Accuracy of Lightgbm cross-vaild test: 0.9408321010888561

[0.9725 0.974  0.9685 0.9735 0.969 ]
Accuracy of Lightgbm cross-vaild test: 0.9715


In [149]:
# Frequency encoding 後 MLP
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes = (256,128,64,32), activation="relu",max_iter=50, random_state=1)
clf43b=MLP.fit(X4b,y)
scores43b = cross_val_score(clf43b,X4b,y,cv=5,scoring='accuracy')
print(scores43b)
print('Accuracy of MLP cross-vaild test:',scores43b.mean())
# Accuracy of MLP cross-vaild test: 0.8364296276381233

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.967  0.967  0.9095 0.9645 0.9665]
Accuracy of MLP cross-vaild test: 0.9549


In [150]:
# Frequency encoding 後 SVM
from sklearn import svm
from sklearn import svm, metrics
from sklearn.metrics import accuracy_score

svm = svm.SVC(kernel='rbf',max_iter=10000) #Default: rbf
clf44b=svm.fit(X4b,y)
scores44b = cross_val_score(clf44b,X4b,y,cv=5,scoring='accuracy')
print(scores44b)
print('Accuracy of SVM cross-vaild test:',scores44b.mean())
# Accuracy of SVM cross-vaild test for one-hot encoding: 0.8364296276381233

[0.967  0.967  0.9665 0.9665 0.9665]
Accuracy of SVM cross-vaild test: 0.9667


## P4：Target Encoding

In [151]:
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [152]:
df= pd.read_csv('Default_Fin.csv')
df=df.dropna(axis=0) #有遺失值，即丟棄該樣本
y=df['Defaulted?']#應變數
X=df.drop(columns='Defaulted?')
X=X.drop(columns='Index') #丟棄應變數
X

Employed  Bank Balance  Annual Salary
0            1       8754.36      532339.56
1            0       9806.16      145273.56
2            1      12882.60      381205.68
3            1       6351.00      428453.88
4            1       9427.92      461562.00
...        ...           ...            ...
9995         1       8538.72      635908.56
9996         1       9095.52      235928.64
9997         1      10144.92      703633.92
9998         1      18828.12      440029.32
9999         0       2411.04      202355.40

[10000 rows x 3 columns]

In [153]:
# Target encoding：使用 Target (預測目標) 來達成 Features 的 Encoding
# 清除 Label Encoder
# 類別特徵：workclass, marital-status, occupation, relationship, race, sex, native-country
from category_encoders import *

enc = TargetEncoder(cols=['Employed'],
                    min_samples_leaf=20, smoothing=10).fit(X, y)
X4c = enc.transform(X)

In [154]:
X4c

Employed  Bank Balance  Annual Salary
0     0.029195       8754.36      532339.56
1     0.043139       9806.16      145273.56
2     0.029195      12882.60      381205.68
3     0.029195       6351.00      428453.88
4     0.029195       9427.92      461562.00
...        ...           ...            ...
9995  0.029195       8538.72      635908.56
9996  0.029195       9095.52      235928.64
9997  0.029195      10144.92      703633.92
9998  0.029195      18828.12      440029.32
9999  0.043139       2411.04      202355.40

[10000 rows x 3 columns]

In [155]:
# Target encoding 後 XGBoost / 前處理在 P2
from xgboost import XGBClassifier

params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf4= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores4c = cross_val_score(clf4,X4c,y,cv=5,scoring='accuracy')
print(scores4c)
print('Accuracy of XGBoost cross-vaild test:',scores4c.mean())

# Accuracy of XGBoost cross-vaild test: 0.9512770533673882

[0.968  0.971  0.963  0.967  0.9675]
Accuracy of XGBoost cross-vaild test: 0.9673


In [156]:
# One hot encoding 後 RandomForest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100)
clf41=RF.fit(X4c,y)
scores41c = cross_val_score(clf41,X4c,y,cv=5,scoring='accuracy')
print(scores41c)
print('Accuracy of RandomForest cross-vaild test:',scores41c.mean())

# Accuracy of RandomForest cross-vaild test for target encoding: 0.8591567243513352

[0.9715 0.969  0.969  0.9675 0.968 ]
Accuracy of RandomForest cross-vaild test: 0.969


In [157]:
# One hot encoding 後 Lightgbm
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(application='multiclass', boosting='gbdt', learning_rate=0.1, max_depth=-5, feature_fraction=0.5, random_state=42)
clf42=LGBM.fit(X4c,y)
scores42c = cross_val_score(clf42,X4c,y,cv=5,scoring='accuracy')
print(scores42c)
print('Accuracy of Lightgbm cross-vaild test:',scores42c.mean())
# Accuracy of Lightgbm cross-vaild test: 0.9454765425460412
# Accuracy of Lightgbm cross-vaild test for target encoding: 0.8740826747563275

[0.9725 0.974  0.9685 0.9735 0.969 ]
Accuracy of Lightgbm cross-vaild test: 0.9715


In [158]:
# One hot encoding 後 MLP
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes = (256,128,64,32), activation="relu",max_iter=50, random_state=1)
clf43=MLP.fit(X4c,y)
scores43c = cross_val_score(clf43,X4c,y,cv=5,scoring='accuracy')
print(scores43c)
print('Accuracy of MLP cross-vaild test:',scores43c.mean())
# Accuracy of MLP cross-vaild test: 0.5685979298292781 

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.967  0.9525 0.9665 0.956  0.8995]
Accuracy of MLP cross-vaild test: 0.9483


In [159]:
# One hot encoding 後 SVM
from sklearn import svm
from sklearn import svm, metrics
from sklearn.metrics import accuracy_score

svm = svm.SVC(kernel='rbf',max_iter=10000) #Default: rbf
clf44=svm.fit(X4c,y)
scores44c = cross_val_score(clf44,X4c,y,cv=5,scoring='accuracy')
print(scores44c)
print('Accuracy of SVM cross-vaild test:',scores44c.mean())
# Accuracy of SVM cross-vaild test: 0.8364296276381233

[0.967  0.967  0.9665 0.9665 0.9665]
Accuracy of SVM cross-vaild test: 0.9667


## P4：Leave-One-Out Encoding

In [160]:
X

Employed  Bank Balance  Annual Salary
0            1       8754.36      532339.56
1            0       9806.16      145273.56
2            1      12882.60      381205.68
3            1       6351.00      428453.88
4            1       9427.92      461562.00
...        ...           ...            ...
9995         1       8538.72      635908.56
9996         1       9095.52      235928.64
9997         1      10144.92      703633.92
9998         1      18828.12      440029.32
9999         0       2411.04      202355.40

[10000 rows x 3 columns]

In [161]:
encc = LeaveOneOutEncoder(cols=['Employed'],sigma=0.05).fit(X, y)
X4d = encc.transform(X)

Source：http://contrib.scikit-learn.org/category_encoders/leaveoneout.html 

In [162]:
# One hot encoding 後 XGBoost
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf4= XGBClassifier(**params)

# 5-fold validation
scores4d = cross_val_score(clf4,X4d,y,cv=5,scoring='accuracy')
print(scores4d)
print('Accuracy of XGBoost cross-vaild test:',scores4d.mean())

# Accuracy of XGBoost cross-vaild test for LOO encoding:  0.9466258905766904

[0.968  0.971  0.963  0.967  0.9675]
Accuracy of XGBoost cross-vaild test: 0.9673


In [163]:
# One hot encoding 後 RandomForest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100)
clf41=RF.fit(X4d,y)
scores41d = cross_val_score(clf41,X4d,y,cv=5,scoring='accuracy')
print(scores41d)
print('Accuracy of RandomForest cross-vaild test:',scores41d.mean())

# Accuracy of RandomForest cross-vaild test: 0.9559214948245731

[0.9715 0.9705 0.9675 0.969  0.9675]
Accuracy of RandomForest cross-vaild test: 0.9692000000000001


In [164]:
# One hot encoding 後 Lightgbm
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(application='multiclass', boosting='gbdt', learning_rate=0.1, max_depth=-5, feature_fraction=0.5, random_state=42)
clf42=LGBM.fit(X4d,y)
scores42d = cross_val_score(clf42,X4d,y,cv=5,scoring='accuracy')
print(scores42d)
print('Accuracy of Lightgbm cross-vaild test:',scores42d.mean())
# Accuracy of Lightgbm cross-vaild test: 0.9454899852130663

[0.9725 0.974  0.9685 0.9735 0.969 ]
Accuracy of Lightgbm cross-vaild test: 0.9715


In [165]:
# One hot encoding 後 MLP
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes = (256,128,64,32), activation="relu",max_iter=50, random_state=1)
clf43=MLP.fit(X4d,y)
scores43d = cross_val_score(clf43,X4d,y,cv=5,scoring='accuracy')
print(scores43d)
print('Accuracy of MLP cross-vaild test:',scores43d.mean())
# Accuracy of MLP cross-vaild test: 0.5685979298292781

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.967  0.9525 0.9665 0.956  0.8995]
Accuracy of MLP cross-vaild test: 0.9483


In [166]:
# One hot encoding 後 SVM
from sklearn import svm
from sklearn import svm, metrics
from sklearn.metrics import accuracy_score

svm = svm.SVC(kernel='rbf',max_iter=10000) #Default: rbf
clf44=svm.fit(X4d,y)
scores44d = cross_val_score(clf44,X4d,y,cv=5,scoring='accuracy')
print(scores44d)
print('Accuracy of SVM cross-vaild test:',scores44d.mean())
# Accuracy of SVM cross-vaild test: 0.8364296276381233

[0.967  0.967  0.9665 0.9665 0.9665]
Accuracy of SVM cross-vaild test: 0.9667


## P6：Categorical values of a feature is high (超過20種)

這邊為 native country 共有 42種類別，所以將其進行 encoding，所有 label encoder 的結果視為 baseline

In [187]:
# Standardization *  Label Encoding
# Standardization *  Label Encoding
df= pd.read_csv('Default_Fin.csv')

df = df.dropna(axis=0) #有遺失值，即丟棄該樣本
y=df['Defaulted?']#應變數
X=df.drop(columns='Defaulted?')
X=X.drop(columns='Index')


X6 = pd.DataFrame(X)

disc6a = KBinsDiscretizer(n_bins=30, encode='ordinal', strategy='quantile')
disc6a.fit(X6[['Bank Balance']])
X6[['Bank Balance']] = disc6a.transform(X6[['Bank Balance']])

/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_discretization.py:230: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(


In [188]:
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [189]:
# One Hot Encoder
from category_encoders import * 
enc6 = OneHotEncoder(cols=['Bank Balance']).fit(X,y)
X6 = enc6.transform(X)

In [190]:
X6

Employed  Bank Balance_1  Bank Balance_2  Bank Balance_3  \
0            1               1               0               0   
1            0               0               1               0   
2            1               0               0               1   
3            1               0               0               0   
4            1               0               1               0   
...        ...             ...             ...             ...   
9995         1               1               0               0   
9996         1               0               0               0   
9997         1               0               0               0   
9998         1               0               0               0   
9999         0               0               0               0   

      Bank Balance_4  Bank Balance_5  Bank Balance_6  Bank Balance_7  \
0                  0               0               0               0   
1                  0               0               0               0   
2                  0               0               0               0   
3                  1               0               0               0   
4                  0               0               0               0   
...              ...             ...             ...             ...   
9995               0               0               0               0   
9996               0               0               0               0   
9997               0               0               1               0   
9998               0               0               0               0   
9999               0               0               0               0   

      Bank Balance_8  Bank Balance_9  ...  Bank Balance_21  Bank Balance_22  \
0                  0               0  ...                0                0   
1                  0               0  ...                0                0   
2                  0               0  ...                0                0   
3                  0               0  ...                0                0   
4                  0               0  ...                0                0   
...              ...             ...  ...              ...              ...   
9995               0               0  ...                0                0   
9996               0               0  ...                0                0   
9997               0               0  ...                0                0   
9998               0               0  ...                0                0   
9999               0               0  ...                0                0   

      Bank Balance_23  Bank Balance_24  Bank Balance_25  Bank Balance_26  \
0                   0                0                0                0   
1                   0                0                0                0   
2                   0                0                0                0   
3                   0                0                0                0   
4                   0                0                0                0   
...               ...              ...              ...              ...   
9995                0                0                0                0   
9996                0                0                0                0   
9997                0                0                0                0   
9998                0                0                0                0   
9999                0                0                0                0   

      Bank Balance_27  Bank Balance_28  Bank Balance_29  Annual Salary  
0                   0                0                0      532339.56  
1                   0                0                0      145273.56  
2                   0                0                0      381205.68  
3                   0                0                0      428453.88  
4                   0                0                0      461562.00  
...               ...              ...          

In [191]:
# XGBoost 
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf6= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores6 = cross_val_score(clf6,X6,y,cv=5,scoring='accuracy')
print(scores6)
print('Accuracy of XGBoost cross-vaild test:',scores6.mean())

# Accuracy of XGBoost cross-vaild test: 0.935031590267509

[0.967  0.965  0.9615 0.9685 0.964 ]
Accuracy of XGBoost cross-vaild test: 0.9652000000000001


In [192]:
# Target Encoder
enc6a = TargetEncoder(cols=['Bank Balance'],min_samples_leaf=20, smoothing=10).fit(X, y)
X6a = enc6a.transform(X)

In [193]:
# XGBoost 
scores6a = cross_val_score(clf6,X6a,y,cv=5,scoring='accuracy')
print(scores6a)
print('Accuracy of XGBoost cross-vaild test:',scores6a.mean())

# Accuracy of XGBoost cross-vaild test: 0.9396894743917192

[0.9675 0.967  0.9605 0.9685 0.9635]
Accuracy of XGBoost cross-vaild test: 0.9654


## P7：Undersampling

In [194]:
X

Employed  Bank Balance  Annual Salary
0            1          11.0      532339.56
1            0          13.0      145273.56
2            1          19.0      381205.68
3            1           7.0      428453.88
4            1          13.0      461562.00
...        ...           ...            ...
9995         1          11.0      635908.56
9996         1          12.0      235928.64
9997         1          14.0      703633.92
9998         1          26.0      440029.32
9999         0           2.0      202355.40

[10000 rows x 3 columns]

In [195]:
# 記得跑上面
# Nearmiss
from imblearn.under_sampling import NearMiss
nm = NearMiss(sampling_strategy = 'majority')
X7, y7 = nm.fit_resample(X, y)

In [196]:
# XGBoost 
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf7= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores7 = cross_val_score(clf7,X7,y7,cv=5,scoring='accuracy')
print(scores7)
print('Accuracy of XGBoost cross-vaild test:',scores7.mean())

# Accuracy of XGBoost cross-vaild test: 0.957330827067669

[0.85820896 0.90977444 0.87218045 0.87218045 0.83458647]
Accuracy of XGBoost cross-vaild test: 0.8693861519470317


In [197]:
# ClusterCentroids
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(voting='hard')
X7a, y7a = cc.fit_resample(X, y)

In [198]:
scores7a = cross_val_score(clf7,X7a,y7a,cv=5,scoring='accuracy')
print(scores7a)
print('Accuracy of XGBoost cross-vaild test:',scores7a.mean())

# Accuracy of XGBoost cross-vaild test: 0.7978070175438596

[0.79850746 0.84210526 0.82706767 0.86466165 0.84210526]
Accuracy of XGBoost cross-vaild test: 0.8348894624621254


In [199]:
# EditedNN
from imblearn.under_sampling import EditedNearestNeighbours
en = EditedNearestNeighbours(kind_sel="all")
X7c, y7c = en.fit_resample(X, y)

In [200]:
scores7c = cross_val_score(clf7,X7c,y7c,cv=5,scoring='accuracy')
print(scores7c)
print('Accuracy of XGBoost cross-vaild test:',scores7c.mean())

# Accuracy: 0.9586666666666668

[0.96600877 0.96710526 0.95942982 0.97039474 0.96160176]
Accuracy of XGBoost cross-vaild test: 0.9649080703679109


In [201]:
# Neighbourhood Cleaning Rule
from imblearn.under_sampling import NeighbourhoodCleaningRule
ecr = NeighbourhoodCleaningRule()
X7d, y7d = ecr.fit_resample(X, y)

In [202]:
scores7d = cross_val_score(clf7,X7d,y7d,cv=5,scoring='accuracy')
print(scores7d)
print('Accuracy of XGBoost cross-vaild test:',scores7d.mean())

# Accuracy: 0.9472198368398456

[0.9686641  0.9675646  0.9582188  0.96976361 0.96316658]
Accuracy of XGBoost cross-vaild test: 0.9654755360087961


In [203]:
# Tomek Links
from imblearn.under_sampling import TomekLinks
tl = TomekLinks()
X7e, y7e = tl.fit_resample(X, y)

In [204]:
scores7e = cross_val_score(clf7,X7e,y7e,cv=5,scoring='accuracy')
print(scores7e)
print('Accuracy of XGBoost cross-vaild test:',scores7e.mean())

# Accuracy: 0.9322485207100591

[0.97096281 0.96637799 0.96281202 0.96839959 0.96381244]
Accuracy of XGBoost cross-vaild test: 0.9664729711694898


In [205]:
# One Sided Selection
from imblearn.under_sampling import OneSidedSelection
oss = OneSidedSelection()
X7f, y7f = oss.fit_resample(X, y)

In [206]:
scores7f = cross_val_score(clf7,X7f,y7f,cv=5,scoring='accuracy')
print(scores7f)
print('Accuracy of XGBoost cross-vaild test:',scores7f.mean())

# Accuracy: 0.9385542168674699

[0.97040816 0.96581633 0.96071429 0.97090352 0.96579888]
Accuracy of XGBoost cross-vaild test: 0.9667282349386921


## P7：Oversampling

In [207]:
# SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X7g, y7g = smote.fit_resample(X, y)

In [208]:
# XGBoost 
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf7= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores7g = cross_val_score(clf7,X7g,y7g,cv=5,scoring='accuracy')
print(scores7g)
print('Accuracy of XGBoost cross-vaild test:',scores7g.mean())

# Accuracy: 0.948709630911188

[0.9524179  0.9837083  0.98215671 0.98293251 0.97904811]
Accuracy of XGBoost cross-vaild test: 0.9760527048415693


In [209]:
# Borderline-SMOTE
from imblearn.over_sampling import BorderlineSMOTE
bsmote = BorderlineSMOTE()
X7h, y7h = bsmote.fit_resample(X, y)

In [210]:
scores7h = cross_val_score(clf7,X7h,y7h,cv=5,scoring='accuracy')
print(scores7h)
print('Accuracy of XGBoost cross-vaild test:',scores7h.mean())

# Accuracy: 0.9473327566320646

[0.93871218 0.98862167 0.98500129 0.98888027 0.98965339]
Accuracy of XGBoost cross-vaild test: 0.9781737601959408


In [211]:
# ADASYN
from imblearn.over_sampling import ADASYN
adasyn = ADASYN()
X7i, y7i = adasyn.fit_resample(X, y)

In [212]:
scores7i = cross_val_score(clf7,X7i,y7i,cv=5,scoring='accuracy')
print(scores7i)
print('Accuracy of XGBoost cross-vaild test:',scores7i.mean())

# Accuracy: 0.9323432664896079

[0.94379391 0.97058824 0.97345133 0.97188964 0.98152004]
Accuracy of XGBoost cross-vaild test: 0.9682486312383652


## P7：Ensemble

In [213]:
# SMOTE + ENN
from imblearn.combine import SMOTEENN
smotenn = SMOTEENN(smote = SMOTE(), enn = EditedNearestNeighbours(sampling_strategy='all'))
X7j, y7j = smotenn.fit_resample(X, y)

In [214]:
scores7j = cross_val_score(clf7,X7j,y7j,cv=5,scoring='accuracy')
print(scores7j)
print('Accuracy of XGBoost cross-vaild test:',scores7j.mean())

# Accuracy: 0.9785811232163164

[0.95658466 0.98914616 0.99059334 0.99131693 0.9942071 ]
Accuracy of XGBoost cross-vaild test: 0.9843696392324611


In [215]:
# SMOTE + Tomek Links
from imblearn.combine import SMOTETomek
smotetl = SMOTETomek(smote = SMOTE(), tomek = TomekLinks(sampling_strategy='majority'))
X7k, y7k = smotetl.fit_resample(X, y)

In [216]:
scores7k = cross_val_score(clf7,X7k,y7k,cv=5,scoring='accuracy')
print(scores7k)
print('Accuracy of XGBoost cross-vaild test:',scores7k.mean())

# Accuracy: 0.9412366580787633

[0.9563854  0.98831243 0.98460661 0.98232611 0.98260622]
Accuracy of XGBoost cross-vaild test: 0.9788473549724138


SMOTE+ENN 效果最好

## P9：Imbalance Ratio vs. Resampling Strategy

In [ ]:
# 見 P7
# 要與其他資料集比較

## P10：ML algorithms vs. different resampling strategies (ENN)

In [221]:
# 使用方法 (參考最好的組合與相關的方法)
# ENN
# Tomek Links
# One Sided Selection
# SMOTE
# Borderline-SMOTE
# SMOTE + ENN
# SMOTE + Tomek Links

In [222]:
# ENN
from imblearn.under_sampling import EditedNearestNeighbours
en = EditedNearestNeighbours(kind_sel="all")
X0, y0 = en.fit_resample(X, y)

In [223]:
# XGBoost Accuracy: 0.8589394520028113
# Random Forest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100)
clf0=RF.fit(X0,y0)
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores0 = cross_val_score(clf0,X0,y0,cv=5,scoring='accuracy')
print(scores0)
print('Accuracy of RandomForest cross-vaild test:',scores0.mean())

# Accuracy of RandomForest cross-vaild test : 0.952

[0.95888158 0.95339912 0.95504386 0.95942982 0.95392211]
Accuracy of RandomForest cross-vaild test: 0.956135298476581


In [224]:
# Lightgbm
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(application='multiclass', boosting='gbdt', learning_rate=0.1, max_depth=-5, feature_fraction=0.5, random_state=42)
clf0a=LGBM.fit(X0,y0)
scores0a = cross_val_score(clf0a,X0,y0,cv=5,scoring='accuracy')
print(scores0a)
print('Accuracy of Lightgbm cross-vaild test:',scores0a.mean())
# Accuracy of Lightgbm cross-vaild test : 0.9426666666666668

[0.96765351 0.96765351 0.96381579 0.96765351 0.9621503 ]
Accuracy of Lightgbm cross-vaild test: 0.9657853234979934


In [225]:
# MLP
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes = (256,128,64,32), activation="relu",max_iter=50, random_state=1)
clf0b=MLP.fit(X0,y0)
scores0b = cross_val_score(clf0b,X0,y0,cv=5,scoring='accuracy')
print(scores0b)
print('Accuracy of MLP cross-vaild test:',scores0b.mean())
# Accuracy of MLP cross-vaild test: 0.8733333333333334

[0.96381579 0.96326754 0.96326754 0.96326754 0.96379594]
Accuracy of MLP cross-vaild test: 0.9634828723619251


In [226]:
# SVM
from sklearn import svm
from sklearn import svm, metrics
from sklearn.metrics import accuracy_score

svm = svm.SVC(kernel='rbf',max_iter=10000) #Default: rbf
clf0c=svm.fit(X0,y0)
scores0c = cross_val_score(clf0c,X0,y0,cv=5,scoring='accuracy')
print(scores0c)
print('Accuracy of SVM cross-vaild test:',scores0c.mean())
# Accuracy of SVM cross-vaild test : 0.852

[0.96381579 0.96326754 0.96326754 0.96326754 0.96379594]
Accuracy of SVM cross-vaild test: 0.9634828723619251


## P10：Tomek Links

In [227]:
from imblearn.under_sampling import TomekLinks
tl = TomekLinks()
X01, y01 = tl.fit_resample(X, y)

In [228]:
scores01 = cross_val_score(clf0,X01,y01,cv=5,scoring='accuracy')
print(scores01)
print('Accuracy of RandomForest cross-vaild test:',scores01.mean())

# Accuracy of RandomForest cross-vaild test : 0.9370245139475909

[0.96281202 0.95720835 0.95262354 0.95973496 0.95565749]
Accuracy of RandomForest cross-vaild test: 0.9576072738111744


In [229]:
scores01a = cross_val_score(clf0a,X01,y01,cv=5,scoring='accuracy')
print(scores01a)
print('Accuracy of Lightgbm cross-vaild test:',scores0a.mean())
# Accuracy of Lightgbm cross-vaild test :  0.9426666666666668

[0.97045339 0.96994396 0.96484972 0.97043833 0.96636086]
Accuracy of Lightgbm cross-vaild test: 0.9657853234979934


In [230]:
scores01b = cross_val_score(clf0b,X01,y01,cv=5,scoring='accuracy')
print(scores01b)
print('Accuracy of MLP cross-vaild test:',scores01b.mean())
# Accuracy of MLP cross-vaild test: 0.8692096365173289

[0.96586857 0.96586857 0.96586857 0.96636086 0.96636086]
Accuracy of MLP cross-vaild test: 0.9660654836181903


In [231]:
scores01c = cross_val_score(clf0c,X01,y01,cv=5,scoring='accuracy')
print(scores01c)
print('Accuracy of SVM cross-vaild test:',scores01c.mean())
# Accuracy of SVM cross-vaild test : 0.8478021978021978

[0.96586857 0.96586857 0.96586857 0.96636086 0.96636086]
Accuracy of SVM cross-vaild test: 0.9660654836181903


## P10：One Sided Selection

In [232]:
from imblearn.under_sampling import OneSidedSelection
oss = OneSidedSelection()
X02, y02 = oss.fit_resample(X, y)

In [233]:
scores02 = cross_val_score(clf0,X02,y02,cv=5,scoring='accuracy')
print(scores02)
print('Accuracy of RandomForest cross-vaild test:',scores02.mean())
# Accuracy of RandomForest cross-vaild test : 0.9268595339441598

[0.96273609 0.95507912 0.95303726 0.9596733  0.95607763]
Accuracy of RandomForest cross-vaild test: 0.9573206817386662


In [234]:
scores02a = cross_val_score(clf0a,X02,y02,cv=5,scoring='accuracy')
print(scores02a)
print('Accuracy of Lightgbm cross-vaild test:',scores0a.mean())
# Accuracy of Lightgbm cross-vaild test : 0.9426666666666668

[0.97039306 0.96937213 0.96477795 0.96988259 0.96731359]
Accuracy of Lightgbm cross-vaild test: 0.9657853234979934


In [235]:
scores02b = cross_val_score(clf0b,X02,y02,cv=5,scoring='accuracy')
print(scores02b)
print('Accuracy of MLP cross-vaild test:',scores02b.mean())
# Accuracy of MLP cross-vaild test:  0.8573118822595773

[0.96630934 0.96579888 0.96579888 0.96579888 0.96629213]
Accuracy of MLP cross-vaild test: 0.9659996214532753


In [236]:
scores02c = cross_val_score(clf0c,X02,y02,cv=5,scoring='accuracy')
print(scores02c)
print('Accuracy of SVM cross-vaild test:',scores02c.mean())
# Accuracy of SVM cross-vaild test : 0.8441165861048987

[0.96630934 0.96579888 0.96579888 0.96579888 0.96629213]
Accuracy of SVM cross-vaild test: 0.9659996214532753


## P10：SMOTE

In [237]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X03, y03 = smote.fit_resample(X, y)

In [238]:
scores03 = cross_val_score(clf0,X03,y03,cv=5,scoring='accuracy')
print(scores03)
print('Accuracy of RandomForest cross-vaild test:',scores03.mean())
# Accuracy of RandomForest cross-vaild test : 0.9403714917339485

[0.94931471 0.97103698 0.97026118 0.97284717 0.97309881]
Accuracy of RandomForest cross-vaild test: 0.9673117713374781


In [239]:
scores03a = cross_val_score(clf0a,X03,y03,cv=5,scoring='accuracy')
print(scores03a)
print('Accuracy of Lightgbm cross-vaild test:',scores03a.mean())
# Accuracy of Lightgbm cross-vaild test : 0.9535539215686274

[0.93974657 0.97543315 0.97362296 0.96870959 0.97439214]
Accuracy of Lightgbm cross-vaild test: 0.9663808839998229


In [240]:
scores03b = cross_val_score(clf0b,X03,y03,cv=5,scoring='accuracy')
print(scores03b)
print('Accuracy of MLP cross-vaild test:',scores03b.mean())
# Accuracy of MLP cross-vaild test: 0.8217920991926182

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.4998707 0.4998707 0.4998707 0.5001293 0.5      ]
Accuracy of MLP cross-vaild test: 0.49994828032066196


In [241]:
scores03c = cross_val_score(clf0c,X03,y03,cv=5,scoring='accuracy')
print(scores03c)
print('Accuracy of SVM cross-vaild test:',scores03c.mean())
# Accuracy of SVM cross-vaild test : 0.6685097078046904

/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider

[0.5327127  0.53504008 0.56684769 0.54745281 0.52095189]
Accuracy of SVM cross-vaild test: 0.5406010319052628


## P10：Borderline-SMOTE

In [242]:
from imblearn.over_sampling import BorderlineSMOTE
bsmote = BorderlineSMOTE()
X04, y04 = bsmote.fit_resample(X, y)

In [243]:
scores04 = cross_val_score(clf0,X04,y04,cv=5,scoring='accuracy')
print(scores04)
print('Accuracy of RandomForest cross-vaild test:',scores04.mean())
# Accuracy of RandomForest cross-vaild test : 0.9396914648212226

[0.93819498 0.97957073 0.97905353 0.98138092 0.97956544]
Accuracy of RandomForest cross-vaild test: 0.9715531194953358


In [244]:
scores04a = cross_val_score(clf0a,X04,y04,cv=5,scoring='accuracy')
print(scores04a)
print('Accuracy of Lightgbm cross-vaild test:',scores04a.mean())
# Accuracy of Lightgbm cross-vaild test : 0.948027201076509

[0.94595294 0.9837083  0.98241531 0.98163951 0.97982411]
Accuracy of Lightgbm cross-vaild test: 0.9747080333130388


In [245]:
scores04b = cross_val_score(clf0b,X04,y04,cv=5,scoring='accuracy')
print(scores04b)
print('Accuracy of MLP cross-vaild test:',scores04b.mean())
# Accuracy of MLP cross-vaild test: 0.8252619184928873

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.50581846 0.4998707  0.4998707  0.4998707  0.5       ]
Accuracy of MLP cross-vaild test: 0.5010861132660978


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [246]:
scores04c = cross_val_score(clf0c,X04,y04,cv=5,scoring='accuracy')
print(scores04c)
print('Accuracy of SVM cross-vaild test:',scores04c.mean())
# Accuracy of SVM cross-vaild test : 0.6733732218377547

/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider

[0.60693044 0.62011896 0.6121024  0.60434445 0.60294878]
Accuracy of SVM cross-vaild test: 0.6092890069192797


## P10：SMOTE + ENN

In [247]:
from imblearn.combine import SMOTEENN
smotenn = SMOTEENN(smote = SMOTE(), enn = EditedNearestNeighbours(sampling_strategy='all'))
X05, y05 = smotenn.fit_resample(X, y)

In [248]:
scores05 = cross_val_score(clf0,X05,y05,cv=5,scoring='accuracy')
print(scores05)
print('Accuracy of RandomForest cross-vaild test:',scores05.mean())
# Accuracy of RandomForest cross-vaild test : 0.9791304347826086

[0.95447871 0.98310066 0.97942689 0.9808964  0.98236591]
Accuracy of RandomForest cross-vaild test: 0.9760537136358879


In [249]:
scores05a = cross_val_score(clf0a,X05,y05,cv=5,scoring='accuracy')
print(scores05a)
print('Accuracy of Lightgbm cross-vaild test:',scores05a.mean())
# Accuracy of Lightgbm cross-vaild test : 0.982608695652174

[0.96549192 0.98383542 0.98310066 0.98016165 0.98163115]
Accuracy of Lightgbm cross-vaild test: 0.9788441598936604


In [250]:
scores05b = cross_val_score(clf0b,X05,y05,cv=5,scoring='accuracy')
print(scores05b)
print('Accuracy of MLP cross-vaild test:',scores05b.mean())
# Accuracy of MLP cross-vaild test:  0.8626086956521739

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.52936858 0.47024247 0.47024247 0.52975753 0.52975753]
Accuracy of MLP cross-vaild test: 0.5058737151248164


In [251]:
scores05c = cross_val_score(clf0c,X05,y05,cv=5,scoring='accuracy')
print(scores05c)
print('Accuracy of SVM cross-vaild test:',scores05c.mean())
# Accuracy of SVM cross-vaild test : 0.7417391304347826

[0.61306902 0.61131521 0.62527553 0.61204996 0.60396767]
Accuracy of SVM cross-vaild test: 0.6131354784693384


## P10：SMOTE + Tomek Links

In [252]:
from imblearn.combine import SMOTETomek
smotetl = SMOTETomek(smote = SMOTE(), tomek = TomekLinks(sampling_strategy='majority'))
X06, y06 = smotetl.fit_resample(X, y)

In [253]:
scores06 = cross_val_score(clf0,X06,y06,cv=5,scoring='accuracy')
print(scores06)
print('Accuracy of RandomForest cross-vaild test:',scores06.mean())
# Accuracy of RandomForest cross-vaild test : 0.9413830072366658

[0.95052902 0.97798113 0.97969688 0.98112668 0.98055476]
Accuracy of RandomForest cross-vaild test: 0.9739776951672863


In [254]:
scores06a = cross_val_score(clf0a,X06,y06,cv=5,scoring='accuracy')
print(scores06a)
print('Accuracy of Lightgbm cross-vaild test:',scores06a.mean())
# Accuracy of Lightgbm cross-vaild test : 0.9490777515167759

[0.94395196 0.98084072 0.97855305 0.97340578 0.97426365]
Accuracy of Lightgbm cross-vaild test: 0.9702030311695738


In [255]:
scores06b = cross_val_score(clf0b,X06,y06,cv=5,scoring='accuracy')
print(scores06b)
print('Accuracy of MLP cross-vaild test:',scores06b.mean())
# Accuracy of MLP cross-vaild test: 0.7955191150313101

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.55275951 0.5570489  0.55533314 0.44695453 0.55333143]
Accuracy of MLP cross-vaild test: 0.533085501858736


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [256]:
scores06c = cross_val_score(clf0c,X06,y06,cv=5,scoring='accuracy')
print(scores06c)
print('Accuracy of SVM cross-vaild test:',scores06c.mean())
# Accuracy of SVM cross-vaild test : 0.6887673302307448

/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider

[0.55275951 0.55275951 0.55275951 0.55304547 0.55304547]
Accuracy of SVM cross-vaild test: 0.5528738919073491


## 輸出

In [257]:
data=pd.DataFrame([[scores1.mean(),scores11.mean()],
         [scores1.mean(),scores2.mean()],         
         [scores3.mean(),scores31.mean()],
         [scores4.mean(),scores41.mean(),scores42.mean(),scores43.mean(),scores44.mean()],
         [scores4a.mean(),scores41a.mean(),scores42a.mean(),scores43a.mean(),scores44a.mean()],
         [scores4b.mean(),scores41b.mean(),scores42b.mean(),scores43b.mean(),scores44b.mean()],
         [scores4c.mean(),scores41c.mean(),scores42c.mean(),scores43c.mean(),scores44c.mean()],
         [scores4d.mean(),scores41d.mean(),scores42d.mean(),scores43d.mean(),scores44d.mean()],
         #[scores5.mean(),scores5a.mean(),scores5b.mean(),scores5c.mean(),scores5d.mean(),scores5e.mean()],
         [scores1.mean(),scores6.mean(),scores6a.mean()],
         [scores7.mean(),scores7a.mean(),#scores7b.mean(),
        scores7c.mean(),scores7d.mean(),scores7e.mean(),scores7f.mean(),scores7g.mean(),scores7h.mean(),scores7i.mean(),scores7j.mean(),scores7k.mean()],
         [scores7g.mean(),scores7h.mean()],
         [scores7.mean(),scores7a.mean(),#scores7b.mean(),
          scores7c.mean(),scores7d.mean(),scores7e.mean(),scores7f.mean(),scores7g.mean(),scores7h.mean(),scores7i.mean(),scores7j.mean(),scores7k.mean()],
         [scores0.mean(),scores0a.mean(),scores0b.mean(),scores0c.mean()],
         [scores01.mean(),scores01a.mean(),scores01b.mean(),scores01c.mean()],
         [scores02.mean(),scores02a.mean(),scores02b.mean(),scores02c.mean()],
         [scores03.mean(),scores03a.mean(),scores03b.mean(),scores03c.mean()],
         [scores04.mean(),scores04a.mean(),scores04b.mean(),scores04c.mean()],
         [scores05.mean(),scores05a.mean(),scores05b.mean(),scores05c.mean()],
         [scores06.mean(),scores06a.mean(),scores06b.mean(),scores06c.mean()]],
         index=['Q1','Q2','Q3','Q4Label','Q4One','Q4F','Q4T','Q4LOL','Q6','Q7','Q8','Q9','Q10-1','Q10-2','Q10-3','Q10-4','Q10-5','Q10-6','Q10-7']     )

In [259]:
data.to_csv('Default_Fin_Result.csv')