## 讀取資料 (Default：Label Encoding)

In [7]:
#讀取資料
import pandas as pd
import numpy as np
# plots
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df= pd.read_csv('HTRU_2.csv')

In [8]:
df

a          b         c         d           e          f  \
0      140.562500  55.683782 -0.234571 -0.699648    3.199833  19.110426   
1      102.507812  58.882430  0.465318 -0.515088    1.677258  14.860146   
2      103.015625  39.341649  0.323328  1.051164    3.121237  21.744669   
3      136.750000  57.178449 -0.068415 -0.636238    3.642977  20.959280   
4       88.726562  40.672225  0.600866  1.123492    1.178930  11.468720   
...           ...        ...       ...       ...         ...        ...   
17893  136.429688  59.847421 -0.187846 -0.738123    1.296823  12.166062   
17894  122.554688  49.485605  0.127978  0.323061   16.409699  44.626893   
17895  119.335938  59.935939  0.159363 -0.743025   21.430602  58.872000   
17896  114.507812  53.902400  0.201161 -0.024789    1.946488  13.381731   
17897   57.062500  85.797340  1.406391  0.089520  188.306020  64.712562   

               g           h  y  
0       7.975532   74.242225  0  
1      10.576487  127.393580  0  
2       7.735822   63.171909  0  
3       6.896499   53.593661  0  
4      14.269573  252.567306  0  
...          ...         ... ..  
17893  15.450260  285.931022  0  
17894   2.945244    8.297092  0  
17895   2.499517    4.595173  0  
17896  10.007967  134.238910  0  
17897  -1.597527    1.429475  0  

[17898 rows x 9 columns]

In [9]:
# 比例
df.y.value_counts()

0    16259
1     1639
Name: y, dtype: int64

In [10]:
# all columns
print(list(df.columns))

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'y']


In [12]:
#資料前處理 
#沒有default LabelEncoder
df=df.dropna(axis=0) #有遺失值，即丟棄該樣本
y=df['y']#應變數
X=df.drop(columns='y')

In [13]:
y

0        0
1        0
2        0
3        0
4        0
        ..
17893    0
17894    0
17895    0
17896    0
17897    0
Name: y, Length: 17898, dtype: int64

In [14]:
X

a          b         c         d           e          f  \
0      140.562500  55.683782 -0.234571 -0.699648    3.199833  19.110426   
1      102.507812  58.882430  0.465318 -0.515088    1.677258  14.860146   
2      103.015625  39.341649  0.323328  1.051164    3.121237  21.744669   
3      136.750000  57.178449 -0.068415 -0.636238    3.642977  20.959280   
4       88.726562  40.672225  0.600866  1.123492    1.178930  11.468720   
...           ...        ...       ...       ...         ...        ...   
17893  136.429688  59.847421 -0.187846 -0.738123    1.296823  12.166062   
17894  122.554688  49.485605  0.127978  0.323061   16.409699  44.626893   
17895  119.335938  59.935939  0.159363 -0.743025   21.430602  58.872000   
17896  114.507812  53.902400  0.201161 -0.024789    1.946488  13.381731   
17897   57.062500  85.797340  1.406391  0.089520  188.306020  64.712562   

               g           h  
0       7.975532   74.242225  
1      10.576487  127.393580  
2       7.735822   63.171909  
3       6.896499   53.593661  
4      14.269573  252.567306  
...          ...         ...  
17893  15.450260  285.931022  
17894   2.945244    8.297092  
17895   2.499517    4.595173  
17896  10.007967  134.238910  
17897  -1.597527    1.429475  

[17898 rows x 8 columns]

In [ ]:
# 差補效果沒有較好
# Missing imputation
#from fancyimpute import KNN
#print(X, '\n')

# Use 3 nearest rows which have a feature to fill in each row's missing features
#imputer = KNN(k=3)

# row’s missing features
#X = imputer.fit_transform(X)
#print(X)

          GEO_X      GEO_Y  DISTRICT_ID  PRECINCT_ID  OFFENSE_CODE  \
0     3132526.0  1698468.0            0            3            40   
1     3158749.0  1672408.0            2           15            17   
2     3173094.0  1663993.0            2           18            15   
3     3152054.0  1712498.0            1            7            15   
4     3157004.0  1674967.0            2           13            15   
...         ...        ...          ...          ...           ...   
1196  3150981.0  1694664.0            5           33             2   
1197  3156774.0  1712483.0            1            7            15   
1198  3143321.0  1692796.0            5           30            15   
1199  3204743.0  1726098.0            4           28            32   
1200  3126994.0  1705528.0            0            0            15   

      NEIGHBORHOOD_ID  
0                  52  
1                  61  
2                  29  
3                  22  
4                  19  
...            

NameError: ignored

## P1：標準化是否影響結果

In [15]:
#先不經標準化做XGBoost
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf1= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores1 = cross_val_score(clf1,X,y,cv=5,scoring='accuracy')
print(scores1)
print('Accuracy of XGBoost cross-vaild test:',scores1.mean())
# Accuracy of XGBoost cross-vaild test: 0.976477621632084

[0.97681564 0.9773743  0.97877095 0.97261805 0.97680916]
Accuracy of XGBoost cross-vaild test: 0.976477621632084


In [16]:
#使用經過LabelEncoder編碼的特徵，標準化 (因為變數值間有大有小)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X1 = sc.fit_transform(X)

In [17]:
#標準化後XGBoost
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf11= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores11 = cross_val_score(clf11,X1,y,cv=5,scoring='accuracy')
print(scores11)
print('Accuracy of XGBoost cross-vaild test:',scores11.mean())

# Accuracy of XGBoost cross-vaild test: 0.976477621632084
##標準化在XGBoost的交叉驗證上沒有差異太大

[0.97681564 0.9773743  0.97877095 0.97261805 0.97680916]
Accuracy of XGBoost cross-vaild test: 0.976477621632084


## P3：Feature Binning 有沒有效果

In [20]:
import pandas as pd
import numpy as np
# For 繪製敘述統計
import matplotlib.pyplot as plt
%matplotlib inline
import pylab
import scipy.stats as stats
from sklearn.model_selection import train_test_split
# for discretization
from sklearn.preprocessing import KBinsDiscretizer

In [22]:
# Equal width Binning
disc1 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
disc1.fit(X[['a']])
disc2 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
disc2.fit(X[['b']])
disc3 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
disc3.fit(X[['c']])
disc4 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
disc4.fit(X[['d']])
disc5 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
disc5.fit(X[['e']])
disc6 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
disc6.fit(X[['f']])
disc7 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
disc7.fit(X[['g']])
disc8 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
disc8.fit(X[['h']])

KBinsDiscretizer(encode='ordinal', n_bins=10, strategy='uniform')

In [23]:
# Equal Frequency Binning
disc11 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
disc11.fit(X[['a']])
disc21 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
disc21.fit(X[['b']])
disc31 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
disc31.fit(X[['c']])
disc41 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
disc41.fit(X[['d']])
disc51 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
disc51.fit(X[['e']])
disc61 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
disc61.fit(X[['f']])
disc71 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
disc71.fit(X[['g']])
disc81 = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
disc81.fit(X[['h']])

KBinsDiscretizer(encode='ordinal', n_bins=10)

In [24]:
disc1.bin_edges_

array([array([  5.8125    ,  24.49296875,  43.1734375 ,  61.85390625,
               80.534375  ,  99.21484375, 117.8953125 , 136.57578125,
              155.25625   , 173.93671875, 192.6171875 ])             ],
      dtype=object)

In [25]:
disc11.bin_edges_

array([array([  5.8125    ,  82.95859375,  96.5625    , 104.415625  ,
              110.1328125 , 115.078125  , 119.8984375 , 124.546875  ,
              129.8953125 , 137.23671875, 192.6171875 ])             ],
      dtype=object)

In [26]:
X3= pd.DataFrame(X)
X3[['a']]=disc1.transform(X[['a']])
X3[['b']]=disc2.transform(X[['b']])
X3[['c']]=disc3.transform(X[['c']])
X3[['d']]=disc4.transform(X[['d']])
X3[['e']]=disc5.transform(X[['e']])
X3[['f']]=disc6.transform(X[['f']])
X3[['g']]=disc7.transform(X[['g']])
X3[['h']]=disc8.transform(X[['h']])
X3= pd.DataFrame(X3)

In [27]:
# Binning 後進行 XGBoost
#X3=X3.drop(columns=['age',' fnlwgt',' capital-gain',' capital-loss',' hours-per-week']) #原先的特徵丟掉

from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf3= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores3 = cross_val_score(clf3,X3,y,cv=5,scoring='accuracy')
print(scores3)
print('Accuracy of XGBoost cross-vaild test:',scores3.mean())

#Accuracy of XGBoost cross-vaild test: 0.9761424104919916
# Frequency較佳

[0.97541899 0.97625698 0.97988827 0.97177983 0.97736798]
Accuracy of XGBoost cross-vaild test: 0.9761424104919916


In [29]:
df= pd.read_csv('HTRU_2.csv')
df=df.dropna(axis=0) #有遺失值，即丟棄該樣本
y=df['y']#應變數
X=df.drop(columns='y')

In [30]:
X31= pd.DataFrame(X)
X31[['a']]=disc11.transform(X[['a']])
X31[['b']]=disc21.transform(X[['b']])
X31[['c']]=disc31.transform(X[['c']])
X31[['d']]=disc41.transform(X[['d']])
X31[['e']]=disc51.transform(X[['e']])
X31[['f']]=disc61.transform(X[['f']])
X31[['g']]=disc71.transform(X[['g']])
X31[['h']]=disc81.transform(X[['h']])
X31= pd.DataFrame(X31)

In [31]:
X31

a    b    c    d    e    f    g    h
0      9.0  9.0  0.0  0.0  5.0  5.0  4.0  4.0
1      2.0  9.0  7.0  0.0  1.0  2.0  7.0  7.0
2      2.0  1.0  6.0  7.0  5.0  6.0  4.0  3.0
3      8.0  9.0  1.0  0.0  6.0  5.0  3.0  3.0
4      1.0  1.0  8.0  7.0  0.0  0.0  9.0  9.0
...    ...  ...  ...  ...  ...  ...  ...  ...
17893  8.0  9.0  0.0  0.0  0.0  1.0  9.0  9.0
17894  6.0  6.0  3.0  5.0  8.0  8.0  1.0  1.0
17895  5.0  9.0  4.0  0.0  8.0  8.0  1.0  1.0
17896  4.0  8.0  4.0  3.0  2.0  1.0  6.0  7.0
17897  0.0  9.0  9.0  4.0  9.0  9.0  0.0  0.0

[17898 rows x 8 columns]

In [32]:
# Binning 後進行 XGBoost
#X3=X3.drop(columns=['age',' fnlwgt',' capital-gain',' capital-loss',' hours-per-week']) #原先的特徵丟掉

from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf3= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores31 = cross_val_score(clf3,X31,y,cv=5,scoring='accuracy')
print(scores31)
print('Accuracy of XGBoost cross-vaild test:',scores31.mean())

#Accuracy of XGBoost cross-vaild test:  0.97401945863596
# Frequency較佳

[0.97402235 0.97290503 0.97486034 0.97233864 0.97597094]
Accuracy of XGBoost cross-vaild test: 0.97401945863596


Source：iT幫幫忙--Day12 - Feature Engineering -- 4. 分隔方法(Discretization),https://ithelp.ithome.com.tw/articles/10235726

## P2：One-hot Encoding vs. Label Encoding on Tree-based method

In [33]:
X

a    b    c    d    e    f    g    h
0      9.0  9.0  0.0  0.0  5.0  5.0  4.0  4.0
1      2.0  9.0  7.0  0.0  1.0  2.0  7.0  7.0
2      2.0  1.0  6.0  7.0  5.0  6.0  4.0  3.0
3      8.0  9.0  1.0  0.0  6.0  5.0  3.0  3.0
4      1.0  1.0  8.0  7.0  0.0  0.0  9.0  9.0
...    ...  ...  ...  ...  ...  ...  ...  ...
17893  8.0  9.0  0.0  0.0  0.0  1.0  9.0  9.0
17894  6.0  6.0  3.0  5.0  8.0  8.0  1.0  1.0
17895  5.0  9.0  4.0  0.0  8.0  8.0  1.0  1.0
17896  4.0  8.0  4.0  3.0  2.0  1.0  6.0  7.0
17897  0.0  9.0  9.0  4.0  9.0  9.0  0.0  0.0

[17898 rows x 8 columns]

In [35]:
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.4/72.4 KB 3.5 MB/s eta 0:00:00


In [36]:
# 續剛剛的binning
from category_encoders import *
enc2 = OneHotEncoder(cols=['a','b','c','d','e','f','g','h']).fit(X,y)
X2 = enc2.transform(X)
X2 = pd.DataFrame(X2)
X2

a_1  a_2  a_3  a_4  a_5  a_6  a_7  a_8  a_9  a_10  ...  h_1  h_2  h_3  \
0        1    0    0    0    0    0    0    0    0     0  ...    1    0    0   
1        0    1    0    0    0    0    0    0    0     0  ...    0    1    0   
2        0    1    0    0    0    0    0    0    0     0  ...    0    0    1   
3        0    0    1    0    0    0    0    0    0     0  ...    0    0    1   
4        0    0    0    1    0    0    0    0    0     0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...  ...  ...  ...   
17893    0    0    1    0    0    0    0    0    0     0  ...    0    0    0   
17894    0    0    0    0    0    0    0    1    0     0  ...    0    0    0   
17895    0    0    0    0    1    0    0    0    0     0  ...    0    0    0   
17896    0    0    0    0    0    0    1    0    0     0  ...    0    1    0   
17897    0    0    0    0    0    0    0    0    0     1  ...    0    0    0   

       h_4  h_5  h_6  h_7  h_8  h_9  h_10  
0        0    0    0    0    0    0     0  
1        0    0    0    0    0    0     0  
2        0    0    0    0    0    0     0  
3        0    0    0    0    0    0     0  
4        1    0    0    0    0    0     0  
...    ...  ...  ...  ...  ...  ...   ...  
17893    1    0    0    0    0    0     0  
17894    0    0    0    0    1    0     0  
17895    0    0    0    0    1    0     0  
17896    0    0    0    0    0    0     0  
17897    0    0    0    0    0    0     1  

[17898 rows x 80 columns]

In [37]:
# One hot encoding 後 XGBoost
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf2= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores2 = cross_val_score(clf2,X2,y,cv=5,scoring='accuracy')
print(scores2)
print('Accuracy of XGBoost cross-vaild test:',scores2.mean())

# Accuracy of XGBoost cross-vaild test for Label Encoder: 
# Accuracy of XGBoost cross-vaild test for one-hot encoding: 0.9750809735873915
# 交叉驗證為 Label Encoder 結果略佳
# 可能在 one-hot encoding 會陷入 curse of dimensionaility

[0.97458101 0.97458101 0.97681564 0.97233864 0.97708857]
Accuracy of XGBoost cross-vaild test: 0.9750809735873915


## P4：Label Encoding

In [39]:
X

a    b    c    d    e    f    g    h
0      9.0  9.0  0.0  0.0  5.0  5.0  4.0  4.0
1      2.0  9.0  7.0  0.0  1.0  2.0  7.0  7.0
2      2.0  1.0  6.0  7.0  5.0  6.0  4.0  3.0
3      8.0  9.0  1.0  0.0  6.0  5.0  3.0  3.0
4      1.0  1.0  8.0  7.0  0.0  0.0  9.0  9.0
...    ...  ...  ...  ...  ...  ...  ...  ...
17893  8.0  9.0  0.0  0.0  0.0  1.0  9.0  9.0
17894  6.0  6.0  3.0  5.0  8.0  8.0  1.0  1.0
17895  5.0  9.0  4.0  0.0  8.0  8.0  1.0  1.0
17896  4.0  8.0  4.0  3.0  2.0  1.0  6.0  7.0
17897  0.0  9.0  9.0  4.0  9.0  9.0  0.0  0.0

[17898 rows x 8 columns]

In [40]:
# XGBoost 
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf4= XGBClassifier(**params)

# 5-fold validation
scores4 = cross_val_score(clf4,X,y,cv=5,scoring='accuracy')
print(scores4)
print('Accuracy of XGBoost cross-vaild test:',scores4.mean())

# Accuracy of XGBoost cross-vaild test: 0.9408522650893938

[0.97402235 0.97290503 0.97486034 0.97233864 0.97597094]
Accuracy of XGBoost cross-vaild test: 0.97401945863596


In [41]:
# RandomForest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100)
clf41=RF.fit(X,y)
scores41 = cross_val_score(clf41,X,y,cv=5,scoring='accuracy')
print(scores41)
print('Accuracy of RandomForest cross-vaild test:',scores41.mean())

# Accuracy of RandomForest cross-vaild test: 0.9327261728726979

[0.97346369 0.97653631 0.97709497 0.9709416  0.97541213]
Accuracy of RandomForest cross-vaild test: 0.9746897404318486


In [42]:
# Lightgbm
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(application='multiclass', boosting='gbdt', learning_rate=0.1, max_depth=-5, feature_fraction=0.5, random_state=42)
clf42=LGBM.fit(X,y)
scores42 = cross_val_score(clf42,X,y,cv=5,scoring='accuracy')
print(scores42)
print('Accuracy of Lightgbm cross-vaild test:',scores42.mean())

# Accuracy of Lightgbm cross-vaild test: 0.9373706143298831

[0.97318436 0.97793296 0.97960894 0.97401509 0.97736798]
Accuracy of Lightgbm cross-vaild test: 0.97642186497586


In [43]:
# One hot encoding 後 MLP
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes = (256,128,64,32), activation="relu",max_iter=50, random_state=1)
clf43=MLP.fit(X,y)
scores43 = cross_val_score(clf43,X,y,cv=5,scoring='accuracy')
print(scores43)
print('Accuracy of MLP cross-vaild test:',scores43.mean())
# Accuracy of MLP cross-vaild test: 0.7034816507595107

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692:

[0.9726257  0.97402235 0.97374302 0.97317687 0.9779268 ]
Accuracy of MLP cross-vaild test: 0.974298944338561


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [44]:
# One hot encoding 後 SVM
from sklearn import svm
from sklearn import svm, metrics
from sklearn.metrics import accuracy_score

svm = svm.SVC(kernel='rbf',max_iter=10000) #Default: rbf
clf44=svm.fit(X,y)
scores44 = cross_val_score(clf44,X,y,cv=5,scoring='accuracy')
print(scores44)
print('Accuracy of SVM cross-vaild test:',scores44.mean())
# Accuracy of SVM cross-vaild test: 0.8364296276381233

[0.97569832 0.97905028 0.9773743  0.97485331 0.97736798]
Accuracy of SVM cross-vaild test: 0.9768688391782605


## P4：One Hot Encoding

In [45]:
X2

a_1  a_2  a_3  a_4  a_5  a_6  a_7  a_8  a_9  a_10  ...  h_1  h_2  h_3  \
0        1    0    0    0    0    0    0    0    0     0  ...    1    0    0   
1        0    1    0    0    0    0    0    0    0     0  ...    0    1    0   
2        0    1    0    0    0    0    0    0    0     0  ...    0    0    1   
3        0    0    1    0    0    0    0    0    0     0  ...    0    0    1   
4        0    0    0    1    0    0    0    0    0     0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...  ...  ...  ...   
17893    0    0    1    0    0    0    0    0    0     0  ...    0    0    0   
17894    0    0    0    0    0    0    0    1    0     0  ...    0    0    0   
17895    0    0    0    0    1    0    0    0    0     0  ...    0    0    0   
17896    0    0    0    0    0    0    1    0    0     0  ...    0    1    0   
17897    0    0    0    0    0    0    0    0    0     1  ...    0    0    0   

       h_4  h_5  h_6  h_7  h_8  h_9  h_10  
0        0    0    0    0    0    0     0  
1        0    0    0    0    0    0     0  
2        0    0    0    0    0    0     0  
3        0    0    0    0    0    0     0  
4        1    0    0    0    0    0     0  
...    ...  ...  ...  ...  ...  ...   ...  
17893    1    0    0    0    0    0     0  
17894    0    0    0    0    1    0     0  
17895    0    0    0    0    1    0     0  
17896    0    0    0    0    0    0     0  
17897    0    0    0    0    0    0     1  

[17898 rows x 80 columns]

In [46]:
# One hot encoding 後 XGBoost / 前處理在 P2
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf4= XGBClassifier(**params)

# 5-fold validation
scores4a = cross_val_score(clf4,X2,y,cv=5,scoring='accuracy')
print(scores4a)
print('Accuracy of XGBoost cross-vaild test:',scores4a.mean())
# Accuracy of XGBoost cross-vaild test: 0.9420217771205808

[0.97458101 0.97458101 0.97681564 0.97233864 0.97708857]
Accuracy of XGBoost cross-vaild test: 0.9750809735873915


In [47]:
# One hot encoding 後 RandomForest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100)
clf41=RF.fit(X2,y)
scores41a = cross_val_score(clf41,X2,y,cv=5,scoring='accuracy')
print(scores41a)
print('Accuracy of RandomForest cross-vaild test:',scores41a.mean())

# Accuracy of RandomForest cross-vaild test: 0.9223215485952412

[0.97430168 0.9773743  0.97681564 0.97122101 0.97652976]
Accuracy of RandomForest cross-vaild test: 0.975248477696557


In [48]:
# One hot encoding 後 Lightgbm
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(application='multiclass', boosting='gbdt', learning_rate=0.1, max_depth=-5, feature_fraction=0.5, random_state=42)
clf42=LGBM.fit(X2,y)
scores42a = cross_val_score(clf42,X2,y,cv=5,scoring='accuracy')
print(scores42a)
print('Accuracy of Lightgbm cross-vaild test:',scores42a.mean())

# Accuracy of Lightgbm cross-vaild test: 0.9362212662992337

[0.97486034 0.97793296 0.97877095 0.9745739  0.97708857]
Accuracy of Lightgbm cross-vaild test: 0.9766453442723773


In [49]:
# One hot encoding 後 MLP
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes = (256,128,64,32), activation="relu",max_iter=50, random_state=1)
clf43=MLP.fit(X2,y)
scores43a = cross_val_score(clf43,X2,y,cv=5,scoring='accuracy')
print(scores43a)
print('Accuracy of MLP cross-vaild test:',scores43a.mean())
# Accuracy of MLP cross-vaild test: 0.8364296276381233

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692:

[0.97290503 0.97150838 0.97513966 0.97122101 0.9745739 ]
Accuracy of MLP cross-vaild test: 0.9730695974812725


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [50]:
# One hot encoding 後 SVM
from sklearn import svm
from sklearn import svm, metrics
from sklearn.metrics import accuracy_score

svm = svm.SVC(kernel='rbf',max_iter=10000) #Default: rbf
clf44=svm.fit(X2,y)
scores44a = cross_val_score(clf44,X2,y,cv=5,scoring='accuracy')
print(scores44a)
print('Accuracy of SVM cross-vaild test:',scores44a.mean())
# Accuracy of SVM cross-vaild test for one-hot encoding: 0.8364296276381233

[0.97486034 0.97877095 0.97765363 0.9745739  0.97625035]
Accuracy of SVM cross-vaild test: 0.9764218337571278


## P4：Frequency Encoding

In [54]:
from pandas.io.formats.printing import enable_data_resource_formatter
X4b = pd.DataFrame(X)

enca=X4b['a'].value_counts()
X4b['a']=X4b['a'].apply(lambda x : enca[x]) 

encb=X4b['b'].value_counts()
X4b['b']=X4b['b'].apply(lambda x : encb[x])

encc=X4b['c'].value_counts()
X4b['c']=X4b['c'].apply(lambda x : encc[x])

encd=X4b['d'].value_counts()
X4b['d']=X4b['d'].apply(lambda x : encd[x]) 

ence=X4b['e'].value_counts()
X4b['e']=X4b['e'].apply(lambda x : ence[x]) 

encf=X4b['f'].value_counts()
X4b['f']=X4b['f'].apply(lambda x : encf[x])

encg=X4b['g'].value_counts()
X4b['g']=X4b['g'].apply(lambda x : encg[x])

ench=X4b['h'].value_counts()
X4b['h']=X4b['h'].apply(lambda x : ench[x]) 

In [55]:
X4b

a     b     c     d     e     f     g     h
0      1790  1791  1790  1790  1790  1790  1791  1791
1      1792  1791  1790  1790  1786  1789  1790  1790
2      1792  1790  1789  1790  1790  1789  1791  1788
3      1790  1791  1790  1790  1789  1790  1788  1788
4      1788  1790  1789  1790  1790  1790  1790  1790
...     ...   ...   ...   ...   ...   ...   ...   ...
17893  1790  1791  1790  1790  1790  1790  1790  1790
17894  1789  1790  1789  1790  1790  1790  1790  1790
17895  1789  1791  1789  1790  1790  1790  1790  1790
17896  1791  1789  1789  1789  1793  1790  1790  1790
17897  1790  1791  1791  1790  1790  1790  1790  1790

[17898 rows x 8 columns]

In [56]:
# Frequency encoding 後 XGBoost / 前處理在 P2
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf4b= XGBClassifier(**params)

# 5-fold validation
scores4b = cross_val_score(clf4b,X4b,y,cv=5,scoring='accuracy')
print(scores4b)
print('Accuracy of XGBoost cross-vaild test:',scores4b.mean())

# Accuracy of XGBoost cross-vaild test: 0.936194380965183

[0.96787709 0.9726257  0.97374302 0.96898575 0.97010338]
Accuracy of XGBoost cross-vaild test: 0.9706669882196113


In [57]:
# Frequency encoding 後 RandomForest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100)
clf41b=RF.fit(X4b,y)
scores41b = cross_val_score(clf41b,X4b,y,cv=5,scoring='accuracy')
print(scores41b)
print('Accuracy of RandomForest cross-vaild test:',scores41b.mean())

# Accuracy of RandomForest cross-vaild test: 0.9315633821750235

[0.96759777 0.97178771 0.97346369 0.96619167 0.97038279]
Accuracy of RandomForest cross-vaild test: 0.9698847248302871


In [58]:
# Frequency encoding 後 Lightgbm
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(application='multiclass', boosting='gbdt', learning_rate=0.1, max_depth=-5, feature_fraction=0.5, random_state=42)
clf42b=LGBM.fit(X4b,y)
scores42b = cross_val_score(clf42b,X4b,y,cv=5,scoring='accuracy')
print(scores42b)
print('Accuracy of Lightgbm cross-vaild test:',scores42b.mean())
# Accuracy of Lightgbm cross-vaild test: 0.9408321010888561

[0.96648045 0.97094972 0.9726257  0.96647108 0.97289746]
Accuracy of Lightgbm cross-vaild test: 0.9698848809239496


In [59]:
# Frequency encoding 後 MLP
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes = (256,128,64,32), activation="relu",max_iter=50, random_state=1)
clf43b=MLP.fit(X4b,y)
scores43b = cross_val_score(clf43b,X4b,y,cv=5,scoring='accuracy')
print(scores43b)
print('Accuracy of MLP cross-vaild test:',scores43b.mean())
# Accuracy of MLP cross-vaild test: 0.8364296276381233

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.90837989 0.90837989 0.90837989 0.9086337  0.90835429]
Accuracy of MLP cross-vaild test: 0.9084255300550541


In [60]:
# Frequency encoding 後 SVM
from sklearn import svm
from sklearn import svm, metrics
from sklearn.metrics import accuracy_score

svm = svm.SVC(kernel='rbf',max_iter=10000) #Default: rbf
clf44b=svm.fit(X4b,y)
scores44b = cross_val_score(clf44b,X4b,y,cv=5,scoring='accuracy')
print(scores44b)
print('Accuracy of SVM cross-vaild test:',scores44b.mean())
# Accuracy of SVM cross-vaild test for one-hot encoding: 0.8364296276381233

[0.95977654 0.95446927 0.96564246 0.95557418 0.96423582]
Accuracy of SVM cross-vaild test: 0.9599396541901001


## P4：Target Encoding

In [61]:
# Target encoding：使用 Target (預測目標) 來達成 Features 的 Encoding
# 清除 Label Encoder
# 類別特徵：workclass, marital-status, occupation, relationship, race, sex, native-country
from category_encoders import *

enc = TargetEncoder(cols=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],min_samples_leaf=20, smoothing=10).fit(X, y)
X4c = enc.transform(X)

In [62]:
X4c

a         b         c         d         e         f         g  \
0      0.240968  0.049135  0.007402  0.110265  0.160670  0.110684  0.013959   
1      0.039621  0.049135  0.007402  0.110265  0.008399  0.015092  0.123943   
2      0.039621  0.138212  0.020263  0.110265  0.160670  0.015092  0.013959   
3      0.240968  0.049135  0.007402  0.110265  0.018446  0.110684  0.022371   
4      0.088926  0.138212  0.020263  0.110265  0.160670  0.110684  0.123943   
...         ...       ...       ...       ...       ...       ...       ...   
17893  0.240968  0.049135  0.007402  0.110265  0.160670  0.110684  0.123943   
17894  0.007546  0.138212  0.020263  0.110265  0.160670  0.110684  0.123943   
17895  0.007546  0.049135  0.020263  0.110265  0.160670  0.110684  0.123943   
17896  0.021217  0.027949  0.020263  0.016769  0.007250  0.110684  0.123943   
17897  0.240968  0.049135  0.402289  0.110265  0.160670  0.110684  0.123943   

              h  
0      0.010609  
1      0.124262  
2      0.025168  
3      0.025168  
4      0.124262  
...         ...  
17893  0.124262  
17894  0.124262  
17895  0.124262  
17896  0.124262  
17897  0.124262  

[17898 rows x 8 columns]

In [63]:
# Target encoding 後 XGBoost / 前處理在 P2
from xgboost import XGBClassifier

params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf4= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores4c = cross_val_score(clf4,X4c,y,cv=5,scoring='accuracy')
print(scores4c)
print('Accuracy of XGBoost cross-vaild test:',scores4c.mean())

# Accuracy of XGBoost cross-vaild test: 0.9512770533673882

[0.96648045 0.97234637 0.97458101 0.96786812 0.9709416 ]
Accuracy of XGBoost cross-vaild test: 0.9704435089230943


In [64]:
# One hot encoding 後 RandomForest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100)
clf41=RF.fit(X4c,y)
scores41c = cross_val_score(clf41,X4c,y,cv=5,scoring='accuracy')
print(scores41c)
print('Accuracy of RandomForest cross-vaild test:',scores41c.mean())

# Accuracy of RandomForest cross-vaild test for target encoding: 0.8591567243513352

[0.96731844 0.97178771 0.97234637 0.9670299  0.96982397]
Accuracy of RandomForest cross-vaild test: 0.9696612767525027


In [65]:
# One hot encoding 後 Lightgbm
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(application='multiclass', boosting='gbdt', learning_rate=0.1, max_depth=-5, feature_fraction=0.5, random_state=42)
clf42=LGBM.fit(X4c,y)
scores42c = cross_val_score(clf42,X4c,y,cv=5,scoring='accuracy')
print(scores42c)
print('Accuracy of Lightgbm cross-vaild test:',scores42c.mean())
# Accuracy of Lightgbm cross-vaild test: 0.9454765425460412
# Accuracy of Lightgbm cross-vaild test for target encoding: 0.8740826747563275

[0.96592179 0.97150838 0.97318436 0.96647108 0.97289746]
Accuracy of Lightgbm cross-vaild test: 0.969996612767525


In [66]:
# One hot encoding 後 MLP
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes = (256,128,64,32), activation="relu",max_iter=50, random_state=1)
clf43=MLP.fit(X4c,y)
scores43c = cross_val_score(clf43,X4c,y,cv=5,scoring='accuracy')
print(scores43c)
print('Accuracy of MLP cross-vaild test:',scores43c.mean())
# Accuracy of MLP cross-vaild test: 0.5685979298292781 

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692:

[0.96731844 0.97402235 0.97821229 0.96926516 0.9709416 ]
Accuracy of MLP cross-vaild test: 0.9719519668581936


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [67]:
# One hot encoding 後 SVM
from sklearn import svm
from sklearn import svm, metrics
from sklearn.metrics import accuracy_score

svm = svm.SVC(kernel='rbf',max_iter=10000) #Default: rbf
clf44=svm.fit(X4c,y)
scores44c = cross_val_score(clf44,X4c,y,cv=5,scoring='accuracy')
print(scores44c)
print('Accuracy of SVM cross-vaild test:',scores44c.mean())
# Accuracy of SVM cross-vaild test: 0.8364296276381233

[0.96620112 0.96955307 0.97513966 0.96898575 0.9709416 ]
Accuracy of SVM cross-vaild test: 0.9701642417516206


## P4：Leave-One-Out Encoding

In [68]:
encc = LeaveOneOutEncoder(cols=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],sigma=0.05).fit(X, y)
X4d = encc.transform(X)

Source：http://contrib.scikit-learn.org/category_encoders/leaveoneout.html 

In [69]:
# One hot encoding 後 XGBoost
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf4= XGBClassifier(**params)

# 5-fold validation
scores4d = cross_val_score(clf4,X4d,y,cv=5,scoring='accuracy')
print(scores4d)
print('Accuracy of XGBoost cross-vaild test:',scores4d.mean())

# Accuracy of XGBoost cross-vaild test for LOO encoding:  0.9466258905766904

[0.96648045 0.97234637 0.97458101 0.96786812 0.9709416 ]
Accuracy of XGBoost cross-vaild test: 0.9704435089230943


In [70]:
# One hot encoding 後 RandomForest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100)
clf41=RF.fit(X4d,y)
scores41d = cross_val_score(clf41,X4d,y,cv=5,scoring='accuracy')
print(scores41d)
print('Accuracy of RandomForest cross-vaild test:',scores41d.mean())

# Accuracy of RandomForest cross-vaild test: 0.9559214948245731

[0.96759777 0.97206704 0.97234637 0.96675049 0.97010338]
Accuracy of RandomForest cross-vaild test: 0.969773008596078


In [71]:
# One hot encoding 後 Lightgbm
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(application='multiclass', boosting='gbdt', learning_rate=0.1, max_depth=-5, feature_fraction=0.5, random_state=42)
clf42=LGBM.fit(X4d,y)
scores42d = cross_val_score(clf42,X4d,y,cv=5,scoring='accuracy')
print(scores42d)
print('Accuracy of Lightgbm cross-vaild test:',scores42d.mean())
# Accuracy of Lightgbm cross-vaild test: 0.9454899852130663

[0.96592179 0.97150838 0.97318436 0.96647108 0.97289746]
Accuracy of Lightgbm cross-vaild test: 0.969996612767525


In [72]:
# One hot encoding 後 MLP
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes = (256,128,64,32), activation="relu",max_iter=50, random_state=1)
clf43=MLP.fit(X4d,y)
scores43d = cross_val_score(clf43,X4d,y,cv=5,scoring='accuracy')
print(scores43d)
print('Accuracy of MLP cross-vaild test:',scores43d.mean())
# Accuracy of MLP cross-vaild test: 0.5685979298292781

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692:

[0.96731844 0.97402235 0.97821229 0.96926516 0.9709416 ]
Accuracy of MLP cross-vaild test: 0.9719519668581936


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [73]:
# One hot encoding 後 SVM
from sklearn import svm
from sklearn import svm, metrics
from sklearn.metrics import accuracy_score

svm = svm.SVC(kernel='rbf',max_iter=10000) #Default: rbf
clf44=svm.fit(X4d,y)
scores44d = cross_val_score(clf44,X4d,y,cv=5,scoring='accuracy')
print(scores44d)
print('Accuracy of SVM cross-vaild test:',scores44d.mean())
# Accuracy of SVM cross-vaild test: 0.8364296276381233

[0.96620112 0.96955307 0.97513966 0.96898575 0.9709416 ]
Accuracy of SVM cross-vaild test: 0.9701642417516206


## P6：Categorical values of a feature is high (超過20種)

這邊為binning其中一個特徵(a)為30組

In [75]:
# Standardization *  Label Encoding
df= pd.read_csv('HTRU_2.csv')

df = df.dropna(axis=0) #有遺失值，即丟棄該樣本
y=df['y']#應變數
X=df.drop(columns='y')

X6 = pd.DataFrame(X)

disc6a = KBinsDiscretizer(n_bins=30, encode='ordinal', strategy='quantile')
disc6a.fit(X6[['a']])
X6[['a']] = disc6a.transform(X6[['a']])

In [76]:
# One Hot Encoder
from category_encoders import * 
enc6 = OneHotEncoder(cols=['a']).fit(X6,y)
X6 = enc6.transform(X6)

In [77]:
X6

a_1  a_2  a_3  a_4  a_5  a_6  a_7  a_8  a_9  a_10  ...  a_28  a_29  \
0        1    0    0    0    0    0    0    0    0     0  ...     0     0   
1        0    1    0    0    0    0    0    0    0     0  ...     0     0   
2        0    1    0    0    0    0    0    0    0     0  ...     0     0   
3        0    0    1    0    0    0    0    0    0     0  ...     0     0   
4        0    0    0    1    0    0    0    0    0     0  ...     0     0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...   ...   ...   
17893    0    0    1    0    0    0    0    0    0     0  ...     0     0   
17894    0    0    0    0    0    0    0    0    0     0  ...     0     0   
17895    0    0    0    0    0    1    0    0    0     0  ...     0     0   
17896    0    0    0    0    0    0    0    0    0     0  ...     0     0   
17897    0    0    0    0    0    0    0    0    0     0  ...     0     0   

       a_30          b         c         d           e          f          g  \
0         0  55.683782 -0.234571 -0.699648    3.199833  19.110426   7.975532   
1         0  58.882430  0.465318 -0.515088    1.677258  14.860146  10.576487   
2         0  39.341649  0.323328  1.051164    3.121237  21.744669   7.735822   
3         0  57.178449 -0.068415 -0.636238    3.642977  20.959280   6.896499   
4         0  40.672225  0.600866  1.123492    1.178930  11.468720  14.269573   
...     ...        ...       ...       ...         ...        ...        ...   
17893     0  59.847421 -0.187846 -0.738123    1.296823  12.166062  15.450260   
17894     0  49.485605  0.127978  0.323061   16.409699  44.626893   2.945244   
17895     0  59.935939  0.159363 -0.743025   21.430602  58.872000   2.499517   
17896     0  53.902400  0.201161 -0.024789    1.946488  13.381731  10.007967   
17897     0  85.797340  1.406391  0.089520  188.306020  64.712562  -1.597527   

                h  
0       74.242225  
1      127.393580  
2       63.171909  
3       53.593661  
4      252.567306  
...           ...  
17893  285.931022  
17894    8.297092  
17895    4.595173  
17896  134.238910  
17897    1.429475  

[17898 rows x 37 columns]

In [78]:
# XGBoost 
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf6= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores6 = cross_val_score(clf6,X6,y,cv=5,scoring='accuracy')
print(scores6)
print('Accuracy of XGBoost cross-vaild test:',scores6.mean())

# Accuracy of XGBoost cross-vaild test: 0.935031590267509

[0.97681564 0.9773743  0.97849162 0.97345627 0.97680916]
Accuracy of XGBoost cross-vaild test: 0.9765894003037582


In [80]:
# Target Encoder
enc6a = TargetEncoder(cols=['a'],min_samples_leaf=20, smoothing=10).fit(X, y)
X6a = enc6a.transform(X)

In [81]:
# XGBoost 
scores6a = cross_val_score(clf6,X6a,y,cv=5,scoring='accuracy')
print(scores6a)
print('Accuracy of XGBoost cross-vaild test:',scores6a.mean())

# Accuracy of XGBoost cross-vaild test: 0.9396894743917192

[0.97541899 0.97765363 0.97877095 0.97625035 0.97764739]
Accuracy of XGBoost cross-vaild test: 0.9771482624433965


## P5：Combinations of numerical and categorical feature transformation

挑選較常用的六個組合

可見第四題

## P7：Undersampling

In [84]:
df= pd.read_csv('HTRU_2.csv')
df=df.dropna(axis=0) #有遺失值，即丟棄該樣本
y=df['y']#應變數
X=df.drop(columns='y')
X

a          b         c         d           e          f  \
0      140.562500  55.683782 -0.234571 -0.699648    3.199833  19.110426   
1      102.507812  58.882430  0.465318 -0.515088    1.677258  14.860146   
2      103.015625  39.341649  0.323328  1.051164    3.121237  21.744669   
3      136.750000  57.178449 -0.068415 -0.636238    3.642977  20.959280   
4       88.726562  40.672225  0.600866  1.123492    1.178930  11.468720   
...           ...        ...       ...       ...         ...        ...   
17893  136.429688  59.847421 -0.187846 -0.738123    1.296823  12.166062   
17894  122.554688  49.485605  0.127978  0.323061   16.409699  44.626893   
17895  119.335938  59.935939  0.159363 -0.743025   21.430602  58.872000   
17896  114.507812  53.902400  0.201161 -0.024789    1.946488  13.381731   
17897   57.062500  85.797340  1.406391  0.089520  188.306020  64.712562   

               g           h  
0       7.975532   74.242225  
1      10.576487  127.393580  
2       7.735822   63.171909  
3       6.896499   53.593661  
4      14.269573  252.567306  
...          ...         ...  
17893  15.450260  285.931022  
17894   2.945244    8.297092  
17895   2.499517    4.595173  
17896  10.007967  134.238910  
17897  -1.597527    1.429475  

[17898 rows x 8 columns]

In [85]:
# 記得跑上面
# Nearmiss
from imblearn.under_sampling import NearMiss
nm = NearMiss(sampling_strategy = 'majority')
X7, y7 = nm.fit_resample(X, y)

In [86]:
# XGBoost 
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf7= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores7 = cross_val_score(clf7,X7,y7,cv=5,scoring='accuracy')
print(scores7)
print('Accuracy of XGBoost cross-vaild test:',scores7.mean())

# Accuracy of XGBoost cross-vaild test: 0.957330827067669

[0.90853659 0.93140244 0.9527439  0.94656489 0.92824427]
Accuracy of XGBoost cross-vaild test: 0.9334984174269223


In [87]:
# ClusterCentroids
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(voting='hard')
X7a, y7a = cc.fit_resample(X, y)

In [88]:
scores7a = cross_val_score(clf7,X7a,y7a,cv=5,scoring='accuracy')
print(scores7a)
print('Accuracy of XGBoost cross-vaild test:',scores7a.mean())

# Accuracy of XGBoost cross-vaild test: 0.7978070175438596

[0.89939024 0.91920732 0.91615854 0.9129771  0.90229008]
Accuracy of XGBoost cross-vaild test: 0.910004654626699


In [89]:
# Condensed Nearest Neighbour (跑不出來先略過)
from imblearn.under_sampling import CondensedNearestNeighbour
cnn = CondensedNearestNeighbour()
X7b, y7b = cnn.fit_resample(X, y)

KeyboardInterrupt: ignored

In [ ]:
scores7b = cross_val_score(clf7,X7b,y7b,cv=5,scoring='accuracy')
print(scores7b)
print('Accuracy of XGBoost cross-vaild test:',scores7b.mean())

# Accuracy of XGBoost cross-vaild test: 0.8144042232277526

In [90]:
# EditedNN
from imblearn.under_sampling import EditedNearestNeighbours
en = EditedNearestNeighbours(kind_sel="all")
X7c, y7c = en.fit_resample(X, y)

In [91]:
scores7c = cross_val_score(clf7,X7c,y7c,cv=5,scoring='accuracy')
print(scores7c)
print('Accuracy of XGBoost cross-vaild test:',scores7c.mean())

# Accuracy: 0.9586666666666668

[0.98013439 0.98393222 0.98451651 0.98568089 0.98597312]
Accuracy of XGBoost cross-vaild test: 0.9840474235468013


In [92]:
# Neighbourhood Cleaning Rule
from imblearn.under_sampling import NeighbourhoodCleaningRule
ecr = NeighbourhoodCleaningRule()
X7d, y7d = ecr.fit_resample(X, y)

In [93]:
scores7d = cross_val_score(clf7,X7d,y7d,cv=5,scoring='accuracy')
print(scores7d)
print('Accuracy of XGBoost cross-vaild test:',scores7d.mean())

# Accuracy: 0.9472198368398456

[0.98092163 0.98473731 0.98649839 0.98473282 0.98414563]
Accuracy of XGBoost cross-vaild test: 0.9842071545905368


In [94]:
# Tomek Links
from imblearn.under_sampling import TomekLinks
tl = TomekLinks()
X7e, y7e = tl.fit_resample(X, y)

In [95]:
scores7e = cross_val_score(clf7,X7e,y7e,cv=5,scoring='accuracy')
print(scores7e)
print('Accuracy of XGBoost cross-vaild test:',scores7e.mean())

# Accuracy: 0.9322485207100591

[0.97800959 0.98082887 0.97829151 0.97659994 0.97715736]
Accuracy of XGBoost cross-vaild test: 0.9781774546016582


In [96]:
# One Sided Selection
from imblearn.under_sampling import OneSidedSelection
oss = OneSidedSelection()
X7f, y7f = oss.fit_resample(X, y)

In [97]:
scores7f = cross_val_score(clf7,X7f,y7f,cv=5,scoring='accuracy')
print(scores7f)
print('Accuracy of XGBoost cross-vaild test:',scores7f.mean())

# Accuracy: 0.9385542168674699

[0.97852501 0.98078553 0.98163323 0.97852501 0.97710571]
Accuracy of XGBoost cross-vaild test: 0.9793148971861791


## P7：Oversampling

In [98]:
# SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X7g, y7g = smote.fit_resample(X, y)

In [99]:
# XGBoost 
from xgboost import XGBClassifier
params = {'objective':'binary:logistic','max_depth': 4,'alpha': 10,'learning_rate': 1.0,'n_estimators':100}  
clf7= XGBClassifier(**params)

# 5-fold validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores7g = cross_val_score(clf7,X7g,y7g,cv=5,scoring='accuracy')
print(scores7g)
print('Accuracy of XGBoost cross-vaild test:',scores7g.mean())

# Accuracy: 0.948709630911188

[0.96786593 0.96663592 0.96571341 0.97016761 0.97062894]
Accuracy of XGBoost cross-vaild test: 0.9682023615176949


In [100]:
# Borderline-SMOTE
from imblearn.over_sampling import BorderlineSMOTE
bsmote = BorderlineSMOTE()
X7h, y7h = bsmote.fit_resample(X, y)

In [101]:
scores7h = cross_val_score(clf7,X7h,y7h,cv=5,scoring='accuracy')
print(scores7h)
print('Accuracy of XGBoost cross-vaild test:',scores7h.mean())

# Accuracy: 0.9473327566320646

[0.8204182  0.98277983 0.98231857 0.98400738 0.98954329]
Accuracy of XGBoost cross-vaild test: 0.9518134548176175


In [102]:
# ADASYN
from imblearn.over_sampling import ADASYN
adasyn = ADASYN()
X7i, y7i = adasyn.fit_resample(X, y)

In [103]:
scores7i = cross_val_score(clf7,X7i,y7i,cv=5,scoring='accuracy')
print(scores7i)
print('Accuracy of XGBoost cross-vaild test:',scores7i.mean())

# Accuracy: 0.9323432664896079

[0.94871003 0.93727792 0.91934487 0.92552534 0.93834981]
Accuracy of XGBoost cross-vaild test: 0.9338415949335616


## P7：Ensemble

In [104]:
# SMOTE + ENN
from imblearn.combine import SMOTEENN
smotenn = SMOTEENN(smote = SMOTE(), enn = EditedNearestNeighbours(sampling_strategy='all'))
X7j, y7j = smotenn.fit_resample(X, y)

In [105]:
scores7j = cross_val_score(clf7,X7j,y7j,cv=5,scoring='accuracy')
print(scores7j)
print('Accuracy of XGBoost cross-vaild test:',scores7j.mean())

# Accuracy: 0.9785811232163164

[0.98528182 0.98879411 0.98762335 0.98812312 0.99013048]
Accuracy of XGBoost cross-vaild test: 0.9879905754673531


In [106]:
# SMOTE + Tomek Links
from imblearn.combine import SMOTETomek
smotetl = SMOTETomek(smote = SMOTE(), tomek = TomekLinks(sampling_strategy='majority'))
X7k, y7k = smotetl.fit_resample(X, y)

In [107]:
scores7k = cross_val_score(clf7,X7k,y7k,cv=5,scoring='accuracy')
print(scores7k)
print('Accuracy of XGBoost cross-vaild test:',scores7k.mean())

# Accuracy: 0.9412366580787633

[0.9675425  0.96738794 0.96846499 0.96630082 0.97031999]
Accuracy of XGBoost cross-vaild test: 0.9680032484016626


SMOTE+ENN 效果最好

## P8：SMOTE‐based Oversampling

參考第七題

## P9：Imbalance Ratio vs. Resampling Strategy

In [ ]:
# 見 P7
# 要與其他資料集比較

## P10：ML algorithms vs. different resampling strategies (ENN)

In [108]:
# 使用方法 (參考最好的組合與相關的方法)
# ENN
# Tomek Links
# One Sided Selection
# SMOTE
# Borderline-SMOTE
# SMOTE + ENN
# SMOTE + Tomek Links

In [109]:
# ENN
from imblearn.under_sampling import EditedNearestNeighbours
en = EditedNearestNeighbours(kind_sel="all")
X0, y0 = en.fit_resample(X, y)

In [110]:
# XGBoost Accuracy: 0.8589394520028113
# Random Forest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100)
clf0=RF.fit(X0,y0)
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
scores0 = cross_val_score(clf0,X0,y0,cv=5,scoring='accuracy')
print(scores0)
print('Accuracy of RandomForest cross-vaild test:',scores0.mean())

# Accuracy of RandomForest cross-vaild test : 0.952

[0.98101081 0.98685364 0.98626935 0.98655757 0.98538866]
Accuracy of RandomForest cross-vaild test: 0.9852160062068522


In [111]:
# Lightgbm
import lightgbm as lgb
LGBM = lgb.LGBMClassifier(application='multiclass', boosting='gbdt', learning_rate=0.1, max_depth=-5, feature_fraction=0.5, random_state=42)
clf0a=LGBM.fit(X0,y0)
scores0a = cross_val_score(clf0a,X0,y0,cv=5,scoring='accuracy')
print(scores0a)
print('Accuracy of Lightgbm cross-vaild test:',scores0a.mean())
# Accuracy of Lightgbm cross-vaild test : 0.9426666666666668

[0.98101081 0.98743792 0.98597721 0.9868498  0.98568089]
Accuracy of Lightgbm cross-vaild test: 0.9853913251933282


In [112]:
# MLP
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes = (256,128,64,32), activation="relu",max_iter=50, random_state=1)
clf0b=MLP.fit(X0,y0)
scores0b = cross_val_score(clf0b,X0,y0,cv=5,scoring='accuracy')
print(scores0b)
print('Accuracy of MLP cross-vaild test:',scores0b.mean())
# Accuracy of MLP cross-vaild test: 0.8733333333333334

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692:

[0.97721297 0.9830558  0.98626935 0.98421975 0.98246639]
Accuracy of MLP cross-vaild test: 0.9826448545806865


In [113]:
# SVM
from sklearn import svm
from sklearn import svm, metrics
from sklearn.metrics import accuracy_score

svm = svm.SVC(kernel='rbf',max_iter=10000) #Default: rbf
clf0c=svm.fit(X0,y0)
scores0c = cross_val_score(clf0c,X0,y0,cv=5,scoring='accuracy')
print(scores0c)
print('Accuracy of SVM cross-vaild test:',scores0c.mean())
# Accuracy of SVM cross-vaild test : 0.852

[0.97341513 0.97838154 0.98247152 0.98071303 0.97866745]
Accuracy of SVM cross-vaild test: 0.9787297330107654


## P10：Tomek Links

In [114]:
from imblearn.under_sampling import TomekLinks
tl = TomekLinks()
X01, y01 = tl.fit_resample(X, y)

In [115]:
scores01 = cross_val_score(clf0,X01,y01,cv=5,scoring='accuracy')
print(scores01)
print('Accuracy of RandomForest cross-vaild test:',scores01.mean())

# Accuracy of RandomForest cross-vaild test : 0.9370245139475909

[0.97885537 0.9850578  0.98280237 0.97857344 0.97884941]
Accuracy of RandomForest cross-vaild test: 0.9808276768766723


In [116]:
scores01a = cross_val_score(clf0a,X01,y01,cv=5,scoring='accuracy')
print(scores01a)
print('Accuracy of Lightgbm cross-vaild test:',scores0a.mean())
# Accuracy of Lightgbm cross-vaild test :  0.9426666666666668

[0.9771638  0.98280237 0.98167465 0.9771638  0.97884941]
Accuracy of Lightgbm cross-vaild test: 0.9853913251933282


In [117]:
scores01b = cross_val_score(clf0b,X01,y01,cv=5,scoring='accuracy')
print(scores01b)
print('Accuracy of MLP cross-vaild test:',scores01b.mean())
# Accuracy of MLP cross-vaild test: 0.8692096365173289

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.97406259 0.9771638  0.97970116 0.9791373  0.97518331]
Accuracy of MLP cross-vaild test: 0.9770496297324573


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [118]:
scores01c = cross_val_score(clf0c,X01,y01,cv=5,scoring='accuracy')
print(scores01c)
print('Accuracy of SVM cross-vaild test:',scores01c.mean())
# Accuracy of SVM cross-vaild test : 0.8478021978021978

[0.97011559 0.97434452 0.97603609 0.97490837 0.97292724]
Accuracy of SVM cross-vaild test: 0.9736663618405391


## P10：One Sided Selection

In [119]:
from imblearn.under_sampling import OneSidedSelection
oss = OneSidedSelection()
X02, y02 = oss.fit_resample(X, y)

In [120]:
scores02 = cross_val_score(clf0,X02,y02,cv=5,scoring='accuracy')
print(scores02)
print('Accuracy of RandomForest cross-vaild test:',scores02.mean())
# Accuracy of RandomForest cross-vaild test : 0.9268595339441598

[0.97792245 0.98499434 0.98159683 0.97961495 0.97933182]
Accuracy of RandomForest cross-vaild test: 0.9806920768717149


In [121]:
scores02a = cross_val_score(clf0a,X02,y02,cv=5,scoring='accuracy')
print(scores02a)
print('Accuracy of Lightgbm cross-vaild test:',scores0a.mean())
# Accuracy of Lightgbm cross-vaild test : 0.9426666666666668

[0.97650722 0.98244621 0.98074745 0.97678369 0.97819932]
Accuracy of Lightgbm cross-vaild test: 0.9853913251933282


In [122]:
scores02b = cross_val_score(clf0b,X02,y02,cv=5,scoring='accuracy')
print(scores02b)
print('Accuracy of MLP cross-vaild test:',scores02b.mean())
# Accuracy of MLP cross-vaild test:  0.8573118822595773

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.97509199 0.9790487  0.97650057 0.97734994 0.9801812 ]
Accuracy of MLP cross-vaild test: 0.9776344795022757


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [123]:
scores02c = cross_val_score(clf0c,X02,y02,cv=5,scoring='accuracy')
print(scores02c)
print('Accuracy of SVM cross-vaild test:',scores02c.mean())
# Accuracy of SVM cross-vaild test : 0.8441165861048987

[0.96999717 0.97423556 0.97593431 0.97480181 0.97281993]
Accuracy of SVM cross-vaild test: 0.973557757804669


## P10：SMOTE

In [124]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X03, y03 = smote.fit_resample(X, y)

In [125]:
scores03 = cross_val_score(clf0,X03,y03,cv=5,scoring='accuracy')
print(scores03)
print('Accuracy of RandomForest cross-vaild test:',scores03.mean())
# Accuracy of RandomForest cross-vaild test : 0.9403714917339485

[0.98201107 0.97739852 0.97478475 0.97370444 0.97801015]
Accuracy of RandomForest cross-vaild test: 0.9771817870416133


In [126]:
scores03a = cross_val_score(clf0a,X03,y03,cv=5,scoring='accuracy')
print(scores03a)
print('Accuracy of Lightgbm cross-vaild test:',scores03a.mean())
# Accuracy of Lightgbm cross-vaild test : 0.9535539215686274

[0.96694342 0.96248462 0.95787208 0.95817315 0.96186376]
Accuracy of Lightgbm cross-vaild test: 0.961467405808919


In [127]:
scores03b = cross_val_score(clf0b,X03,y03,cv=5,scoring='accuracy')
print(scores03b)
print('Accuracy of MLP cross-vaild test:',scores03b.mean())
# Accuracy of MLP cross-vaild test: 0.8217920991926182

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.95325953 0.94895449 0.95187577 0.93910503 0.94633246]
Accuracy of MLP cross-vaild test: 0.9479054562573921


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [128]:
scores03c = cross_val_score(clf0c,X03,y03,cv=5,scoring='accuracy')
print(scores03c)
print('Accuracy of SVM cross-vaild test:',scores03c.mean())
# Accuracy of SVM cross-vaild test : 0.6685097078046904

[0.93419434 0.92312423 0.92619926 0.92080578 0.92495771]
Accuracy of SVM cross-vaild test: 0.9258562657900914


## P10：Borderline-SMOTE

In [129]:
from imblearn.over_sampling import BorderlineSMOTE
bsmote = BorderlineSMOTE()
X04, y04 = bsmote.fit_resample(X, y)

In [130]:
scores04 = cross_val_score(clf0,X04,y04,cv=5,scoring='accuracy')
print(scores04)
print('Accuracy of RandomForest cross-vaild test:',scores04.mean())
# Accuracy of RandomForest cross-vaild test : 0.9396914648212226

[0.81288438 0.98908364 0.98693112 0.98692911 0.99384899]
Accuracy of RandomForest cross-vaild test: 0.953935448281132


In [131]:
scores04a = cross_val_score(clf0a,X04,y04,cv=5,scoring='accuracy')
print(scores04a)
print('Accuracy of Lightgbm cross-vaild test:',scores04a.mean())
# Accuracy of Lightgbm cross-vaild test : 0.948027201076509

[0.81780443 0.97847478 0.97847478 0.97862525 0.98554513]
Accuracy of Lightgbm cross-vaild test: 0.9477848760880351


In [132]:
scores04b = cross_val_score(clf0b,X04,y04,cv=5,scoring='accuracy')
print(scores04b)
print('Accuracy of MLP cross-vaild test:',scores04b.mean())
# Accuracy of MLP cross-vaild test: 0.8252619184928873

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.800123   0.94618696 0.95571956 0.96616946 0.97247424]
Accuracy of MLP cross-vaild test: 0.9281346446403107


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [133]:
scores04c = cross_val_score(clf0c,X04,y04,cv=5,scoring='accuracy')
print(scores04c)
print('Accuracy of SVM cross-vaild test:',scores04c.mean())
# Accuracy of SVM cross-vaild test : 0.6733732218377547

[0.8654674  0.92773678 0.92835178 0.93172382 0.94971552]
Accuracy of SVM cross-vaild test: 0.920599060250175


## P10：SMOTE + ENN

In [134]:
from imblearn.combine import SMOTEENN
smotenn = SMOTEENN(smote = SMOTE(), enn = EditedNearestNeighbours(sampling_strategy='all'))
X05, y05 = smotenn.fit_resample(X, y)

In [135]:
scores05 = cross_val_score(clf0,X05,y05,cv=5,scoring='accuracy')
print(scores05)
print('Accuracy of RandomForest cross-vaild test:',scores05.mean())
# Accuracy of RandomForest cross-vaild test : 0.9791304347826086

[0.98961474 0.99045226 0.98894287 0.99128832 0.99313118]
Accuracy of RandomForest cross-vaild test: 0.9906858747863403


In [136]:
scores05a = cross_val_score(clf0a,X05,y05,cv=5,scoring='accuracy')
print(scores05a)
print('Accuracy of Lightgbm cross-vaild test:',scores05a.mean())
# Accuracy of Lightgbm cross-vaild test : 0.982608695652174

[0.98190955 0.98492462 0.98274418 0.98710002 0.98760261]
Accuracy of Lightgbm cross-vaild test: 0.9848561958729819


In [137]:
scores05b = cross_val_score(clf0b,X05,y05,cv=5,scoring='accuracy')
print(scores05b)
print('Accuracy of MLP cross-vaild test:',scores05b.mean())
# Accuracy of MLP cross-vaild test:  0.8626086956521739

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.96649916 0.97353434 0.96800134 0.96867147 0.97503769]
Accuracy of MLP cross-vaild test: 0.9703488010219188


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [138]:
scores05c = cross_val_score(clf0c,X05,y05,cv=5,scoring='accuracy')
print(scores05c)
print('Accuracy of SVM cross-vaild test:',scores05c.mean())
# Accuracy of SVM cross-vaild test : 0.7417391304347826

[0.95477387 0.95527638 0.95744681 0.9532585  0.95928966]
Accuracy of SVM cross-vaild test: 0.9560090450577567


## P10：SMOTE + Tomek Links

In [139]:
from imblearn.combine import SMOTETomek
smotetl = SMOTETomek(smote = SMOTE(), tomek = TomekLinks(sampling_strategy='majority'))
X06, y06 = smotetl.fit_resample(X, y)

In [140]:
scores06 = cross_val_score(clf0,X06,y06,cv=5,scoring='accuracy')
print(scores06)
print('Accuracy of RandomForest cross-vaild test:',scores06.mean())
# Accuracy of RandomForest cross-vaild test : 0.9413830072366658

[0.98238566 0.9774378  0.97821048 0.97542884 0.98130119]
Accuracy of RandomForest cross-vaild test: 0.9789527929018295


In [141]:
scores06a = cross_val_score(clf0a,X06,y06,cv=5,scoring='accuracy')
print(scores06a)
print('Accuracy of Lightgbm cross-vaild test:',scores06a.mean())
# Accuracy of Lightgbm cross-vaild test : 0.9490777515167759

[0.96878863 0.96383866 0.96028435 0.95688456 0.96461134]
Accuracy of Lightgbm cross-vaild test: 0.9628815086191335


In [142]:
scores06b = cross_val_score(clf0b,X06,y06,cv=5,scoring='accuracy')
print(scores06b)
print('Accuracy of MLP cross-vaild test:',scores06b.mean())
# Accuracy of MLP cross-vaild test: 0.7955191150313101

/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


[0.95101978 0.9344769  0.94560346 0.94591253 0.95425746]
Accuracy of MLP cross-vaild test: 0.9462540250416472


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


In [143]:
scores06c = cross_val_score(clf0c,X06,y06,cv=5,scoring='accuracy')
print(scores06c)
print('Accuracy of SVM cross-vaild test:',scores06c.mean())
# Accuracy of SVM cross-vaild test : 0.6887673302307448

[0.93278739 0.92025962 0.92736826 0.91840519 0.93045897]
Accuracy of SVM cross-vaild test: 0.9258558866514652


## 輸出

In [145]:
data=pd.DataFrame([[scores1.mean(),scores11.mean()],
         [scores1.mean(),scores2.mean()],         
         [scores3.mean(),scores31.mean()],
         [scores4.mean(),scores41.mean(),scores42.mean(),scores43.mean(),scores44.mean()],
         [scores4a.mean(),scores41a.mean(),scores42a.mean(),scores43a.mean(),scores44a.mean()],
         [scores4b.mean(),scores41b.mean(),scores42b.mean(),scores43b.mean(),scores44b.mean()],
         [scores4c.mean(),scores41c.mean(),scores42c.mean(),scores43c.mean(),scores44c.mean()],
         [scores4d.mean(),scores41d.mean(),scores42d.mean(),scores43d.mean(),scores44d.mean()],
         #[scores5.mean(),scores5a.mean(),scores5b.mean(),scores5c.mean(),scores5d.mean(),scores5e.mean()],
         [scores1.mean(),scores6.mean(),scores6a.mean()],
         [scores7.mean(),scores7a.mean(),#scores7b.mean(),
         scores7c.mean(),scores7d.mean(),scores7e.mean(),scores7f.mean(),scores7g.mean(),scores7h.mean(),scores7i.mean(),scores7j.mean(),scores7k.mean()],
         [scores7g.mean(),scores7h.mean()],
         [scores7.mean(),scores7a.mean(),#scores7b.mean(),
         scores7c.mean(),scores7d.mean(),scores7e.mean(),scores7f.mean(),scores7g.mean(),scores7h.mean(),scores7i.mean(),scores7j.mean(),scores7k.mean()],
         [scores0.mean(),scores0a.mean(),scores0b.mean(),scores0c.mean()],
         [scores01.mean(),scores01a.mean(),scores01b.mean(),scores01c.mean()],
         [scores02.mean(),scores02a.mean(),scores02b.mean(),scores02c.mean()],
         [scores03.mean(),scores03a.mean(),scores03b.mean(),scores03c.mean()],
         [scores04.mean(),scores04a.mean(),scores04b.mean(),scores04c.mean()],
         [scores05.mean(),scores05a.mean(),scores05b.mean(),scores05c.mean()],
         [scores06.mean(),scores06a.mean(),scores06b.mean(),scores06c.mean()]],
         index=['Q1','Q2','Q3','Q4Label','Q4One','Q4F','Q4T','Q4LOL','Q6','Q7','Q8','Q9','Q10-1','Q10-2','Q10-3','Q10-4','Q10-5','Q10-6','Q10-7']     )

In [146]:
data.to_csv('HTRU_2_Result.csv')